Repository opentiny/tiny-engine, pull requests merged in 2023-11, with the labels that each got.

#43 fix(page-lock):页面解锁按钮图标修复
  packages/toolbars/lock/src/Main.vue
Labels: bug

#31 fix: 修复无页面时页面内容显示错误问题
  packages/plugins/page/src/PageTree.vue
Labels: bug

#32 fix: 修复不切换页面点击页面设置时表单校验错误问题
  packages/plugins/page/src/Main.vue
Labels: bug

#33 fix(block-list-icon):区块管理面板去掉列表图标
  packages/common/component/PluginBlockList.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/materials/src/block/BlockGroupTransfer.vue
  packages/plugins/materials/src/block/BlockGroupTransferPanel.vue
Labels: bug

#46 feat(docs): add Milestones
  README.en-US.md
  README.md
  README.zh-CN.md
Labels: documentation

#53 feat(chore): update package info
  mockServer/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/controller/package.json
  packages/design-core/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/data/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/dark/package.json
  packages/theme/light/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-vue/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: documentation, ready to merge

#70 fix(toolbars): disable toolbar btn when page is empty
  packages/controller/src/useLayout.js
  packages/toolbars/generate-vue/src/Main.vue
  packages/toolbars/preview/src/Main.vue
  packages/toolbars/refresh/src/Main.vue
  packages/toolbars/setting/src/Main.vue
Labels: bug, ready for review

#54 feat(doc): add doc link to readme
  README.en-US.md
  README.md
  README.zh-CN.md
Labels: documentation, ready for review

#67 fix(style): adjust style detail
  packages/common/component/MetaBindVariable.vue
  packages/design-core/src/DesignSettings.vue
  packages/settings/styles/src/Main.vue
  packages/theme/common/global.less
Labels: bug, ready for review, ready to merge

#75 fix(canvas): change canvas menu item hiding to disabed
  packages/canvas/src/components/container/CanvasMenu.vue
  packages/theme/dark/canvas.less
  packages/theme/dark/variable.less
  packages/theme/light/canvas.less
Labels: enhancement, ready for review, ready to merge

#69 fix(canvas): fix del key error when nothing is selected
  packages/canvas/src/components/container/container.js
Labels: bug, ready for review

#80 feat(chore): add setup script setup environment before serving
  package.json
  scripts/setup.js
Labels: enhancement

#77 fix(pluginMaterial): fix block list can't scroll when visible in canvas
  packages/canvas/src/components/container/CanvasContainer.vue
  packages/plugins/materials/src/Main.vue
  packages/plugins/materials/src/component/Main.vue
Labels: bug, enhancement, ready for review, ready to merge

#85 fix：修复属性面板插槽开关打开后没有插槽拖拽区
  packages/canvas/src/components/render/render.js
Labels: bug, ready for review

#84 fix：时间线步骤条编辑数据，步骤条会消失
  packages/design-core/public/mock/bundle.json
Labels: bug

#74 fix(pagePlugin): 删除文件夹添加节流，避免多次出现无法删除弹窗
  packages/plugins/page/src/PageFolderSetting.vue
Labels: enhancement, ready for review

#87 fix:loading can't be closed when state is saved
  packages/common/component/MetaBindVariable.vue
  packages/controller/src/useSaveLocal.js
  packages/plugins/data/src/Main.vue
  packages/plugins/script/src/js/method.js
  packages/toolbars/save/src/js/index.js
Labels: bug, enhancement, ready for review

#86 fix(metaComponent): fix #79 metaListItems dragging not working
  packages/common/component/MetaContainer.vue
  packages/common/component/MetaListItems.vue
Labels: bug, enhancement, ready for review, ready to merge

#72 fix(pagePlugin): clear some state when delte current page
  packages/controller/src/usePage.js
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageHome.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/page/src/PageTree.vue
Labels: bug, enhancement, ready for review, ready to merge

#37 fix(datasource-newfiled): 数据源面板中，点击新建字段报错
  packages/plugins/datasource/src/DataSourceField.vue
Labels: bug, ready for review, ready to merge

#90 fix：修复组件属性绑定工具类函数，出码预览未定义
  packages/design-core/src/preview/src/preview/srcFiles/lowcode.js
  packages/vue-generator/src/generator/page.js
Labels: enhancement, ready for review

#94 fix(insert-footer-button)：设计器页面设置-输入设置中，保存取消按钮顺序错误，格式化按钮样式错误，应与UI保持一直；大纲书导航中，眼睛图标，建议改为睁开就是可见，闭眼就是不可见；提示框样式修改
  packages/common/component/MetaCodeEditor.vue
  packages/controller/src/useModal.jsx
  packages/plugins/block/src/js/blockSetting.jsx
  packages/plugins/materials/src/block/BlockGroup.vue
  packages/plugins/tree/src/Main.vue
Labels: bug, enhancement, ready_for_review

#102 fix(styles-import): 解决tree组件选中样式背景色为黑色的问题
  packages/design-core/vite.config.js
  packages/plugins/page/src/PageTree.vue
  packages/theme/dark/pageManage.less
  packages/theme/light/pageManage.less
Labels: bug, ready_for_review

#52 feat(builtin): builtinComponent 组件独立包抽离
  packages/builtinComponent/README.md
  packages/builtinComponent/index.js
  packages/builtinComponent/package.json
  packages/builtinComponent/src/components/CanvasCol.vue
  packages/builtinComponent/src/components/CanvasRow.vue
  packages/builtinComponent/src/components/CanvasRowColContainer.vue
  packages/builtinComponent/src/components/helper.js
  packages/builtinComponent/src/meta/CanvasCol.json
  packages/builtinComponent/src/meta/CanvasRow.json
  packages/builtinComponent/src/meta/CanvasRowColContainer.json
  packages/builtinComponent/src/meta/index.js
  packages/builtinComponent/vite.config.js
  packages/canvas/package.json
  packages/canvas/src/components/builtin/builtin.json
  packages/canvas/src/components/builtin/index.js
  packages/canvas/src/components/render/render.js
  packages/controller/package.json
  packages/controller/src/useResource.js
  packages/design-core/vite.config.js
  packages/vue-generator/.gitignore
  packages/vue-generator/package.json
  packages/vue-generator/src/constant/index.js
  packages/vue-generator/src/generator/page.js
  packages/vue-generator/test/testcases/full/case4_canvasrow-component/input/blocks.schema.json
  packages/vue-generator/test/testcases/full/case4_canvasrow-component/input/components-map.json
  packages/vue-generator/test/testcases/full/case4_canvasrow-component/input/page.schema.json
  packages/vue-generator/test/testcases/full/case4_canvasrow-component/output/BuiltInComponent.vue
  packages/vue-generator/test/testcases/full/index.config.js
  packages/vue-generator/test/testcases/full/index.js
Labels: enhancement, refactoring, ready_for_review

#101 添加eslint&自动化构建
  .eslintignore
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md
  .github/workflows/push-check.yml
  CONTRIBUTING.md
  CONTRIBUTING.zh-CN.md
  README.en-US.md
Labels: ci, ready_for_review

#93 fix：组件属性绑定工具类utils，修改预览出码实现
  mockServer/src/mock/get/app-center/apps/extension/list.json
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
  mockServer/src/services/appinfo.json
  packages/design-core/src/preview/src/preview/srcFiles/lowcode.js
  packages/vue-generator/src/generator/page.js
Labels: ready_for_review

#103 fix: 修复空页面执行右键删除和右键复制时控制台报错的问题
  packages/canvas/src/components/container/CanvasMenu.vue
  packages/canvas/src/components/container/container.js
Labels: bug, ready_for_review

#108 fix：修复自定义属性新增功能
  packages/common/component/MetaHtmlAttributes.vue
  packages/common/component/MetaHtmlText.vue
Labels: bug, good first issue, ready_for_review, ready to merge

#81 fix(canvasShortCutPanel): add click event to quick insert component in…
  packages/canvas/src/components/container/CanvasDragItem.vue
  packages/utils/package.json
  packages/utils/src/utils/index.js
  packages/utils/test/deepClone.test.js
  packages/utils/vite.config.js
Labels: bug, enhancement, ready_for_review
