Repository opentiny/tiny-engine, pull requests merged in 2023-12, with the labels that each got.

#106 fix：修复国际化参数配置
  packages/canvas/src/components/render/render.js
  packages/common/component/BindI18n.vue
  packages/vue-generator/src/generator/page.js
Labels: bug, ready_for_review

#41 feat(style): stylePanel add style selector, write css to global styles
  packages/canvas/src/components/container/container.js
  packages/controller/src/useProperties.js
  packages/settings/styles/package.json
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/components/background/BackgroundGroup.vue
  packages/settings/styles/src/components/border/BorderGroup.vue
  packages/settings/styles/src/components/classNamesContainer/index.vue
  packages/settings/styles/src/components/effects/EffectGroup.vue
  packages/settings/styles/src/components/index.js
  packages/settings/styles/src/components/layout/FlexBox.vue
  packages/settings/styles/src/components/layout/GridBox.vue
  packages/settings/styles/src/components/position/PositionGroup.vue
  packages/settings/styles/src/components/size/SizeGroup.vue
  packages/settings/styles/src/components/spacing/SpacingGroup.vue
  packages/settings/styles/src/components/typography/TypographyGroup.vue
  packages/settings/styles/src/js/parser.js
  packages/settings/styles/src/js/useStyle.js
  packages/theme/dark/settings.less
  packages/theme/light/settings.less
Labels: enhancement, ready_for_review

#129 fix: 手动更新画布key导致表格渲染出错
  packages/canvas/src/components/container/container.js
  packages/canvas/src/components/render/runner.js
Labels: bug, ready_for_review

#151 fix(dataSources): 解决collection添加表格时预览报错 #118
  mockServer/src/services/appinfo.json
Labels: bug

#146 feat(block2webcomponent): add block2webcomponent package
  packages/blockToWebComponentTemplate/README.md
  packages/blockToWebComponentTemplate/package.json
  packages/blockToWebComponentTemplate/src/BlockFileName.vue
  packages/blockToWebComponentTemplate/src/lib.js
  packages/blockToWebComponentTemplate/vite.config.js
Labels: ready_for_review

#119 fix：删除lowcodeWrap多余参数
  packages/vue-generator/src/generator/page.js
Labels: bug, ready_for_review, ready to merge

#149 fix(chore): replace unpkg with npmmirror
  packages/design-core/canvas.html
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/importMap.js
  packages/design-core/src/preview/src/preview/srcFiles/app.js
  packages/design-core/vite.config.js
Labels: enhancement, ready_for_review, ready to merge

#160 fix(blockBuild): change packageName to block build
  packages/blockToWebComponentTemplate/package.json
Labels: bug, ready_for_review, ready to merge

#128 fix: 修复画布宽度设置问题
  packages/toolbars/media/src/Main.vue
Labels: bug, ready_for_review

#175 fix: 修复复制静态文件时接口报错
  packages/plugins/page/src/PageSetting.vue
Labels: bug, good first issue

#105 feat：引入第三方组件库element-plus部分组件示例
  mockServer/src/services/appinfo.json
  mockServer/src/services/schema2code.js
  packages/common/component/MetaTableColumns.vue
  packages/common/index.js
  packages/design-core/public/mock/bundle.json
Labels: enhancement

#133 fix: 使用import动态导入有cdn的工具类
  packages/canvas/src/components/container/container.js
  packages/canvas/src/components/render/RenderMain.js
  packages/canvas/src/index.js
  packages/design-core/src/preview/src/preview/generate.js
  packages/plugins/bridge/src/BridgeSetting.vue
  packages/plugins/bridge/src/js/resource.js
  packages/theme/dark/bridge.less
  packages/theme/light/bridge.less
  packages/toolbars/generate-vue/src/generateCode.js
Labels: enhancement, ready_for_review

#170 fix(preview): upgrade vue repl version
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/Preview.vue
Labels: enhancement, ready_for_review

#154 fix:添加style变量赋值
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/js/useStyle.js
  packages/theme/dark/index.less
  packages/theme/dark/setting-style.less
  packages/theme/light/index.less
  packages/theme/light/setting-style.less
Labels: enhancement, ready_for_review, ready to merge

#197 fix: 修复多个全局变量下载代码出错
  packages/toolbars/generate-vue/src/generateCode.js
  packages/toolbars/media/src/Main.vue
Labels: bug, ready_for_review

#205 fix: 精简应用发布时commit消息的校验规则
  packages/toolbars/logo/src/Main.vue
Labels: enhancement, ready_for_review

#206 feat: 开放区块管理相关功能
  packages/canvas/src/components/container/CanvasMenu.vue
  packages/common/component/PluginBlockList.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/materials/src/block/BlockGroup.vue
  packages/plugins/materials/src/block/BlockList.vue
  packages/plugins/materials/src/block/Main.vue
Labels: enhancement, ready_for_review, ready to merge

#195 feat: add materials script
  .env.local
  package.json
  scripts/buildMaterials.mjs
  scripts/connection.mjs
  scripts/logger.mjs
  scripts/splitMaterials.mjs
Labels: enhancement, ready_for_review

#207 doc：README添加物料同步脚本说明
  README.md
  README.zh-CN.md
Labels: documentation, ready_for_review, ready to merge

#201 feat(generate-vue): change generate vue code location
  packages/toolbars/generate-vue/src/generateCode.js
Labels: refactoring, ready_for_review

#208 增加跟本地后端直连的方案
  README.md
  README.zh-CN.md
Labels: documentation, ready_for_review
