Repository opentiny/tiny-engine, pull requests merged in 2024-07, with the labels that each got.

#547 fix(vue-generator): fix globalstate codegen error
  packages/vue-generator/package.json
  packages/vue-generator/src/plugins/genGlobalState.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/stores/index.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/stores/testState.js
  packages/vue-generator/test/testcases/generator/mockData.js
Labels: bug, ready_for_review

#527 fix(material): add componentsMap to app Schema after material build
  scripts/buildMaterials.mjs
Labels: bug

#605 fix: slot params missing double quote
  packages/vue-generator/src/generator/vue/sfc/generateAttribute.js
  packages/vue-generator/test/testcases/sfc/case06/case06.test.js
  packages/vue-generator/test/testcases/sfc/case06/components-map.json
  packages/vue-generator/test/testcases/sfc/case06/expected/slotTest.vue
  packages/vue-generator/test/testcases/sfc/case06/page.schema.json
  packages/vue-generator/vite.config.mjs
Labels: bug, ready_for_review

#606 fix: preserve import.meta.env when compile design-core
  packages/common/vite.config.js
  packages/design-core/vite.config.js
Labels: bug, ready_for_review, ready to merge

#645 fix: fix variable configurator missing problem
  packages/common/component/ConfigItem.vue
Labels: bug, ready to merge

#625 feat(registry): metapp in registry support configuration in array format
  packages/register/src/common.js
  packages/register/src/entryHash.js
  packages/register/test/preprocessRegistry.test.js
Labels: enhancement, ready to merge

#668 fix: esbuild install failed on node v16
  package.json
Labels: bug, ready_for_review

#656 fix: builtin components can't generate import statement with genSFCWithDefaultPlugin method
  packages/vue-generator/src/generator/vue/sfc/genSetupSFC.js
Labels: ready_for_review

#665 fix(preview): multiple nested blocks cannot preview #663
  packages/design-core/src/preview/src/preview/Preview.vue
Labels: bug, ready_for_review

#701 fix(material): add missing componentsMap to mockServer #700
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
  packages/design-core/public/mock/bundle.json
Labels: bug, ready_for_review, ready to merge

#710 workflow: add pr check in ospp-2024 branch
  .github/workflows/push-check.yml
Labels: ospp-2024

#709 workflow: add pr check in ospp-2024 branch
  .github/workflows/push-check.yml
Labels: ospp-2024

#708 workflow: add pr check in ospp-2024 branch
  .github/workflows/push-check.yml
Labels: ospp-2024

#707 workflow: add pr check in ospp-2024 branch
  .github/workflows/push-check.yml
Labels: ospp-2024

#706 workflow: add pr check in ospp-2024 branch
  .github/workflows/push-check.yml
Labels: ospp-2024

#632 refactor：插件面板优化功能
  packages/canvas/src/components/container/CanvasFooter.vue
  packages/common/component/PluginPanel.vue
  packages/common/component/PluginSetting.vue
  packages/controller/src/useLayout.js
  packages/design-core/src/App.vue
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/bridge/src/Main.vue
  packages/plugins/data/src/Main.vue
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceGlobalDataHandler.vue
  packages/plugins/datasource/src/DataSourceRemotePanel.vue
  packages/plugins/datasource/src/Main.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/Main.vue
  packages/plugins/materials/src/component/Main.vue
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageFolderSetting.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/Main.vue
  packages/plugins/tree/src/Main.vue
  packages/settings/events/index.js
  packages/settings/events/src/Main.vue
  packages/settings/props/index.js
  packages/settings/props/src/Main.vue
  packages/settings/styles/index.js
  packages/settings/styles/src/Main.vue
  packages/theme/common/global.less
Labels: ospp-2024

#639 fix: Fixed AI chat function
  packages/plugins/robot/package.json
  packages/plugins/robot/src/ContentDialog.vue
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/TokenDialog.vue
  packages/plugins/robot/src/js/useDialogContent.js
  packages/plugins/robot/src/js/useSpeechRecognition.js
Labels: ospp-2024

#715 fix(setting): fix bindEvent dialog visible can't work on tinyvue 3.17
  packages/settings/events/src/components/BindEventsDialog.vue
Labels: bug, ready_for_review, ready to merge
