Repository opentiny/tiny-engine, pull requests merged in 2024-05, with the labels that each got.

#453 fix(block-diff): 修复区块发布是查看差异保存时schema出错的bug
  packages/common/component/BlockDeployDialog.vue
Labels: bug, ready_for_review, ready to merge

#454 fix(dataSource): 数据源新增字段时，新增的表单设置在列表头部，且数组插入数据时插入到头部
  packages/plugins/datasource/src/DataSourceField.vue
Labels: ready_for_review, ready to merge

#435 fix(reset-button): 修复样式配置中重置按钮的样式和设计稿不一致的问题；
  packages/design-core/src/App.vue
  packages/settings/styles/src/components/inputs/ModalMask.vue
  packages/settings/styles/src/components/inputs/ResetButton.vue
Labels: bug, ready_for_review, ready to merge

#446 Fix/serarch empty:为对部分功能设置搜索为空样式处理
  packages/common/component/PluginBlockList.vue
  packages/common/component/SearchEmpty.vue
  packages/common/index.js
  packages/plugins/bridge/src/BridgeManage.vue
  packages/plugins/data/src/DataSourceList.vue
  packages/plugins/data/src/Main.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/block/BlockVersionSelect.vue
  packages/plugins/materials/src/block/Main.vue
  packages/plugins/materials/src/component/Main.vue
Labels: ready_for_review, ready to merge

#448 修复新增页面搜索条件存在并没有触发
  packages/plugins/page/src/PageHistory.vue
  packages/plugins/page/src/PageTree.vue
Labels: ready_for_review, ready to merge

#436 fix(canvas): add placeholder for empty container #365
  packages/canvas/src/components/render/render.js
  packages/design-core/public/mock/bundle.json
Labels: ready_for_review

#425 feat(canvasApi): use canvasApi to access canvas methods
  packages/canvas/src/components/container/CanvasContainer.vue
  packages/canvas/src/components/container/container.js
  packages/canvas/src/components/render/RenderMain.js
  packages/canvas/src/index.js
  packages/common/component/BlockDeployDialog.vue
  packages/common/component/BlockLinkEvent.vue
  packages/common/component/BlockLinkField.vue
  packages/common/component/LifeCycles.vue
  packages/common/component/MetaBindVariable.vue
  packages/common/component/MetaRelatedEditor.vue
  packages/common/component/MetaSlot.vue
  packages/common/component/MetaTableColumns.vue
  packages/controller/src/useBlock.js
  packages/controller/src/useCanvas.js
  packages/controller/src/useHistory.js
  packages/controller/src/useProperties.js
  packages/controller/src/useResource.js
  packages/controller/src/useTranslate.js
  packages/design-core/src/App.vue
  packages/design-core/src/DesignCanvas.vue
  packages/plugins/bridge/src/js/resource.js
  packages/plugins/data/src/Main.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/datasource/src/DataSourceRecordList.vue
  packages/plugins/materials/src/block/BlockList.vue
  packages/plugins/materials/src/component/Main.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/js/method.js
  packages/plugins/tree/src/Main.vue
  packages/settings/events/src/components/AdvanceConfig.vue
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/components/classNamesContainer/index.vue
  packages/settings/styles/src/js/useEditor.js
  packages/settings/styles/src/js/useStyle.js
  packages/toolbars/generate-vue/src/Main.vue
  packages/toolbars/media/src/Main.vue
  packages/toolbars/preview/src/Main.vue
  packages/toolbars/refresh/src/Main.vue
  packages/toolbars/save/src/js/index.js
Labels: enhancement, ready_for_review

#457 feat(chore): update OpenTinyVue version
  packages/blockToWebComponentTemplate/package.json
  packages/blockToWebComponentTemplate/vite.config.js
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/canvas/src/components/container/CanvasFooter.vue
  packages/common/package.json
  packages/controller/package.json
  packages/design-core/canvas.html
  packages/design-core/package.json
  packages/design-core/src/DesignSettings.vue
  packages/design-core/src/preview/src/preview/importMap.js
  packages/design-core/src/preview/src/preview/srcFiles/app.js
  packages/design-core/vite.config.js
  packages/http/package.json
  packages/plugins/block/package.json
  packages/plugins/block/src/Main.vue
  packages/plugins/bridge/package.json
  packages/plugins/data/package.json
  packages/plugins/data/src/Main.vue
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/materials/src/block/BlockGroup.vue
  packages/plugins/materials/src/block/Main.vue
  packages/plugins/materials/src/component/Main.vue
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/common/global.less
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-vue/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
Labels: ready_for_review

#360 build: 公共依赖cdn解耦并增加开关控制
  .gitignore
  packages/canvas/src/components/common/index.js
  packages/design-core/.env.alpha
  packages/design-core/.env.development
  packages/design-core/.env.prod
  packages/design-core/canvas.html
  packages/design-core/package.json
  packages/design-core/scripts/localCdnFile/copyBundleDeps.js
  packages/design-core/scripts/localCdnFile/copyImportMap.js
  packages/design-core/scripts/localCdnFile/copyPreviewImportMap.js
  packages/design-core/scripts/localCdnFile/index.js
  packages/design-core/scripts/localCdnFile/locateCdnNpmInfo.js
  packages/design-core/scripts/localCdnFile/replaceImportPath.mjs
  packages/design-core/scripts/localCdnFile/utils.js
  packages/design-core/scripts/vite-plugins/configureServerAddProxy.js
  packages/design-core/scripts/vite-plugins/installPackageTemporary.js
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/design-core/src/preview/src/preview/http.js
  packages/design-core/src/preview/src/preview/importMap.js
  packages/design-core/src/preview/src/preview/importMap.json
  packages/design-core/vite.config.js
Labels: enhancement, ready_for_review

#490 fix(chore): remove ai code review workflow
  .github/workflows/ai-code-review.yml
Labels: ready_for_review, ready to merge

#458 fix: 修复画布行列容器组件中的分割工具位置错误的问题
  packages/canvas/src/components/container/CanvasAction.vue
  packages/canvas/src/components/container/CanvasContainer.vue
  packages/canvas/src/components/container/CanvasDivider.vue
  packages/canvas/src/components/container/CanvasMenu.vue
  packages/canvas/src/components/container/CanvasResize.vue
  packages/canvas/src/components/container/CanvasResizeBorder.vue
  packages/canvas/src/components/container/container.js
  packages/design-core/src/DesignCanvas.vue
Labels: bug, ready_for_review

#474 fix: 行列容器组件纵向分割大于2的时候报错
  packages/canvas/src/components/container/CanvasDivider.vue
Labels: bug, ready_for_review

#441 fix: 事件绑定JSX函数时，函数解析报错
  packages/settings/events/src/components/BindEventsDialog.vue
Labels: bug, ready_for_review

#493 fix(setup): add controller to prebuild before start local develop
  scripts/setup.js
Labels: bug, ready_for_review, ready to merge

#496 fix(chore): exclude vue-generator expected folder codecheck
  .codecheck/check.yml
Labels: ci, ready_for_review, ready to merge

#500 fix(build): 修复@babel/template解析占位符时报错问题
  packages/build/vite-plugin-generate-comments/package.json
  packages/build/vite-plugin-generate-comments/src/utils.js
Labels: bug

#504 fix(build): 将generate-comments插件移入devDependencies
  packages/design-core/package.json
Labels: bug

#501 fix(setting-panel): add meta for setting panel
  packages/settings/events/index.js
  packages/settings/events/meta.js
  packages/settings/events/package.json
  packages/settings/events/vite.config.js
  packages/settings/props/index.js
  packages/settings/props/meta.js
  packages/settings/props/package.json
  packages/settings/props/vite.config.js
  packages/settings/styles/index.js
  packages/settings/styles/meta.js
  packages/settings/styles/package.json
  packages/settings/styles/vite.config.js
Labels: ready_for_review

#503 fix(mockServer): mockServer page preview can't render element-plus element
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
Labels: bug, ready_for_review, ready to merge

#515 feat: init function refactor
  designer-demo/engine.config.js
  designer-demo/package.json
  designer-demo/src/App.vue
  designer-demo/src/canvas.js
  designer-demo/src/defineEntry.js
  designer-demo/src/main.js
  designer-demo/vite.config.js
  package.json
  packages/build/vite-plugin-generate-comments/package.json
  packages/design-core/index.js
  packages/design-core/src/index.js
  packages/design-core/src/init.js
  packages/design-core/src/main.js
  scripts/setup.js
Labels: ready_for_review

#516 feat(entry): add plugin correspond method
  packages/design-core/vite.config.js
  packages/entry/src/common.js
  packages/entry/src/index.js
  packages/entry/src/useMessage.js
  packages/entry/src/useShareState.js
  packages/entry/vite.config.js
Labels: ready_for_review

#521 refactor(registry): 更改注册表结构，覆盖配置移至overwrite字段下
  packages/design-core/registry.js
  packages/entry/src/common.js
Labels: ready_for_review

#528 feat: add capability of add custom metaComponents
  designer-demo/package.json
  designer-demo/src/MyInputConfigurator.vue
  designer-demo/src/configurators.js
  designer-demo/src/main.js
  packages/builtinComponent/src/meta/CanvasCol.json
  packages/builtinComponent/src/meta/CanvasRow.json
  packages/builtinComponent/src/meta/CanvasRowColContainer.json
  packages/canvas/src/components/builtin/builtin.json
  packages/common/component/ConfigItem.vue
  packages/common/index.js
  packages/configurator/README.md
  packages/configurator/package.json
  packages/configurator/src/index.js
  packages/configurator/src/input-configurator/InputConfigurator.vue
  packages/configurator/src/input-configurator/index.js
  packages/configurator/src/select-configurator/SelectConfigurator.vue
  packages/configurator/src/select-configurator/index.js
  packages/configurator/vite.config.js
  packages/design-core/public/mock/bundle.json
  packages/design-core/src/init.js
  packages/design-core/src/registerConfigurators.js
  packages/design-core/vite.config.js
  packages/entry/README.md
  packages/entry/src/configurators.js
  packages/entry/src/index.js
Labels: refactoring, ready_for_review
