Repository opentiny/tiny-engine, pull requests merged in 2024-11, with the labels that each got.

#853 feat(style-panel): modify this style-panel styles according to the design craft
  packages/common/component/MetaCodeEditor.vue
  packages/configurator/src/color-configurator/ColorConfigurator.vue
  packages/configurator/src/index.js
  packages/configurator/src/number-configurator/NumberConfigurator.vue
  packages/configurator/src/slider-configurator/SliderConfigurator.vue
  packages/configurator/src/tabs-group-configurator/TabsGroupConfigurator.vue
  packages/design-core/assets/style-panel-collapsed.svg
  packages/design-core/assets/style-panel-expand.svg
  packages/layout/src/DesignSettings.vue
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/components/background/BackgroundGroup.vue
  packages/settings/styles/src/components/background/BackgroundImageGradient.vue
  packages/settings/styles/src/components/background/BackgroundImageSetting.vue
  packages/settings/styles/src/components/background/ImageSetting.vue
  packages/settings/styles/src/components/background/LinearGradient.vue
  packages/settings/styles/src/components/background/PositionOrigin.vue
  packages/settings/styles/src/components/background/RadialGradient.vue
  packages/settings/styles/src/components/border/BorderGroup.vue
  packages/settings/styles/src/components/classNamesContainer/index.vue
  packages/settings/styles/src/components/effects/EffectGroup.vue
  packages/settings/styles/src/components/inputs/InputSelect.vue
  packages/settings/styles/src/components/inputs/ModalMask.vue
  packages/settings/styles/src/components/inputs/NumericSelect.vue
  packages/settings/styles/src/components/inputs/ResetButton.vue
  packages/settings/styles/src/components/layout/FlexBox.vue
  packages/settings/styles/src/components/layout/LayoutGroup.vue
  packages/settings/styles/src/components/position/PositionGroup.vue
  packages/settings/styles/src/components/size/SizeGroup.vue
  packages/settings/styles/src/components/spacing/SpacingGroup.vue
  packages/settings/styles/src/components/spacing/SpacingSetting.vue
  packages/settings/styles/src/components/typography/TypographyGroup.vue
  packages/settings/styles/src/js/cssType.js
  packages/settings/styles/src/js/styleProperty.js
  packages/theme/base/src/common.less
  packages/theme/dark/variable.less
  packages/theme/light/base.less
  packages/theme/light/setting-style.less
  packages/theme/light/variable.less
Labels: ready_for_review, refactor-main

#901 fix：adjust editor style
  packages/common/component/VueMonaco.vue
  packages/plugins/state/src/CreateStore.vue
  packages/plugins/state/src/CreateVariable.vue
Labels: refactor-main

#849 fix: del unnecessary scripts
  package.json
Labels: bug, refactor-main

#900 fix：missing outline tree eyes icon
  packages/plugins/tree/src/Main.vue
Labels: refactor-main

#898 Feat: add refresh life cycles
  packages/build/vite-config/src/vite-plugins/devAliasPlugin.js
  packages/canvas/common/src/constant.js
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/container/src/container.js
  packages/canvas/render/src/RenderMain.js
  packages/canvas/render/src/context.js
  packages/canvas/render/src/render.js
  packages/toolbars/refresh/src/Main.vue
Labels: ready_for_review, refactor-main

#903 fix：the second level panel style of attributes
  packages/theme/base/src/page/base-config-page.less
Labels: refactor-main

#905 fix: monaco editor cursor mismatch caused css font-size
  packages/common/component/MetaCodeEditor.vue
Labels: bug, refactor-main

#912 fix: preview compatibility i18n is null
  packages/design-core/src/preview/src/preview/generate.js
Labels: bug, refactor-main

#909 fix: fix materials panel
  packages/design-core/assets/fixed-solid.svg
  packages/layout/src/DesignPlugins.vue
  packages/plugins/materials/src/components/header/Main.vue
  packages/plugins/materials/src/meta/layout/src/Main.vue
  packages/plugins/tree/src/Main.vue
  packages/utils/src/constants/index.js
Labels: bug, refactor-main
