Repository opentiny/tiny-engine, pull requests merged in 2024-09, with the labels that each got.

#779 fix: github action build too slow
  .github/workflows/push-check.yml
Labels: bug, refactor-main

#778 feat：Drag Handle Check
  packages/common/component/PluginPanel.vue
  packages/controller/src/useLayout.js
  packages/design-core/config/addons.js
Labels: ospp-2024

#657 fix: reset spacing cannot generate correct source code
  packages/settings/styles/src/components/spacing/SpacingGroup.vue
  packages/settings/styles/src/components/spacing/SpacingSetting.vue
  packages/settings/styles/src/js/parser.js
Labels: bug, ready_for_review

#765 feat: optimize material group
  designer-demo/public/mock/bundle.json
  packages/builtinComponent/src/meta/CanvasCol.json
  packages/builtinComponent/src/meta/CanvasRow.json
  packages/builtinComponent/src/meta/CanvasRowColContainer.json
  packages/builtinComponent/src/meta/index.js
  packages/canvas/render/src/builtin/builtin.json
  packages/plugins/materials/src/composable/useMaterial.js
  packages/plugins/materials/src/meta/component/src/Main.vue
Labels: enhancement, refactor-main

#777 feat(mockserver,plugins,controller): 基于模板内容生成页面
  mockServer/src/database/pages.db
  mockServer/src/database/templates.db
  mockServer/src/routes/main-routes.js
  mockServer/src/services/pages.js
  packages/controller/js/http.js
  packages/plugins/page/src/http.js
  packages/plugins/template/src/TemplateGeneral.vue
  packages/plugins/template/src/TemplateSetting.vue
  packages/plugins/template/src/TemplateTree.vue
Labels: ospp-2024

#734 fix: jsx slot modelvalue can't update value
  packages/vue-generator/.eslintrc.cjs
  packages/vue-generator/src/generator/vue/sfc/genSetupSFC.js
  packages/vue-generator/src/generator/vue/sfc/generateAttribute.js
  packages/vue-generator/test/testcases/sfc/slotModelValue/components-map.json
  packages/vue-generator/test/testcases/sfc/slotModelValue/expected/slotModelValueTest.vue
  packages/vue-generator/test/testcases/sfc/slotModelValue/page.schema.json
  packages/vue-generator/test/testcases/sfc/slotModelValue/slotModel.test.js
Labels: bug, ready_for_review

#781 feat: element-plus 物料适配
  packages/design-core/public/mock/bundle.json
  scripts/genMaterial.js
Labels: enhancement, ospp-2024

#788 fix: optimize block and material scalability issue
  packages/canvas/container/src/components/CanvasMenu.vue
  packages/common/component/ProgressBar.vue
  packages/common/component/index.js
  packages/plugins/block/index.js
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/SaveNewBlock.vue
  packages/plugins/materials/src/composable/useMaterial.js
  packages/plugins/materials/src/meta/block/src/BlockPanel.vue
  packages/plugins/materials/src/meta/block/src/Main.vue
Labels: bug, refactor-main

#790 fix(plugins/template): 修复添加模板类别无效问题
  packages/plugins/template/src/TemplateSetting.vue
Labels: ospp-2024

#785 refactor：plugin adjusts to the left and right sides
  packages/common/component/PluginSetting.vue
  packages/design-core/config/addons.js
  packages/design-core/config/plugin.js
  packages/design-core/src/App.vue
  packages/plugins/bridge/src/BridgeSetting.vue
  packages/plugins/data/src/Main.vue
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceGlobalDataHandler.vue
  packages/plugins/datasource/src/DataSourceRecordList.vue
  packages/plugins/datasource/src/DataSourceRemotePanel.vue
  packages/plugins/page/src/PageFolderSetting.vue
  packages/plugins/page/src/PageSetting.vue
Labels: ospp-2024

#718 feat(canvas): add the renderer extension capability
  packages/canvas/render/src/RenderMain.js
  packages/canvas/render/src/runner.js
Labels: refactor-main

#793 bump alpha version
  designer-demo/package.json
  mockServer/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/theme/dark/package.json
  packages/theme/light/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: refactor-main

#794 feat: supports plugin drag and plugin order state is persisted using …
  packages/controller/src/useLayout.js
  packages/design-core/package.json
  packages/design-core/src/App.vue
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/plugins/help/index.js
Labels: enhancement, ospp-2024

#481 fix(stylePanel): fix setting border-radius could not work on first time
  packages/settings/styles/src/components/border/BorderGroup.vue
Labels: bug, ready_for_review

#801 feat(mockServer): 实现基本表单模板
  mockServer/src/database/templates.db
Labels: ospp-2024

#792 Ospp 2024/feat graphic dialogue
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/TokenDialog.vue
  packages/plugins/robot/src/js/robotSetting.js
Labels: ospp-2024

#809 feat(mockServer): 实现官网landing模板
  mockServer/src/database/templates.db
  packages/design-core/public/mock/bundle.json
Labels: ospp-2024

#812 feat(bundle): update label and description of bundle.json
  designer-demo/public/mock/bundle.json
  packages/common/component/ConfigItem.vue
Labels: refactor-main

#808 chore: sync dev to refactor
  README.md
  README.zh-CN.md
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
  package.json
  packages/canvas/container/src/components/CanvasAction.vue
  packages/canvas/container/src/container.js
  packages/canvas/render/src/RenderMain.js
  packages/canvas/render/src/render.js
  packages/common/component/ConfigItem.vue
  packages/common/component/LifeCycles.vue
  packages/configurator/src/html-text-configurator/HtmlTextConfigurator.vue
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/engine-cli/template/designer/public/mock/bundle.json
  packages/settings/events/src/components/BindEventsDialog.vue
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/components/border/BorderGroup.vue
  packages/settings/styles/src/components/spacing/SpacingGroup.vue
  packages/settings/styles/src/components/spacing/SpacingSetting.vue
  packages/settings/styles/src/js/parser.js
  packages/utils/package.json
  packages/utils/src/fs/fszip.js
  packages/utils/src/fs/index.js
  packages/vue-generator/.eslintrc.cjs
  packages/vue-generator/package.json
  packages/vue-generator/src/generator/vue/sfc/genSetupSFC.js
  packages/vue-generator/src/generator/vue/sfc/generateAttribute.js
  packages/vue-generator/src/plugins/genGlobalState.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/stores/index.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/stores/testState.js
  packages/vue-generator/test/testcases/generator/mockData.js
  packages/vue-generator/test/testcases/sfc/case06/case06.test.js
  packages/vue-generator/test/testcases/sfc/case06/components-map.json
  packages/vue-generator/test/testcases/sfc/case06/expected/slotTest.vue
  packages/vue-generator/test/testcases/sfc/case06/page.schema.json
  packages/vue-generator/test/testcases/sfc/slotModelValue/components-map.json
  packages/vue-generator/test/testcases/sfc/slotModelValue/expected/slotModelValueTest.vue
  packages/vue-generator/test/testcases/sfc/slotModelValue/page.schema.json
  packages/vue-generator/test/testcases/sfc/slotModelValue/slotModel.test.js
  packages/vue-generator/vite.config.mjs
  scripts/buildMaterials.mjs
  scripts/connection.mjs
  scripts/splitMaterials.mjs
Labels: refactor-main

#813 chore: bump version
  designer-demo/package.json
  mockServer/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/theme/dark/package.json
  packages/theme/light/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: refactor-main

#736 feat:sort out the status and API of the layout
  designer-demo/registry.js
  packages/layout/index.js
  packages/layout/src/DesignToolbars.vue
  packages/layout/src/Main.vue
  packages/layout/src/ToolbarCollapse.vue
  packages/toolbars/breadcrumb/meta.js
  packages/toolbars/clean/meta.js
  packages/toolbars/collaboration/meta.js
  packages/toolbars/fullscreen/meta.js
  packages/toolbars/generate-code/meta.js
  packages/toolbars/generate-code/src/Main.vue
  packages/toolbars/lang/meta.js
  packages/toolbars/layout/meta.js
  packages/toolbars/lock/meta.js
  packages/toolbars/logo/meta.js
  packages/toolbars/logout/meta.js
  packages/toolbars/media/meta.js
  packages/toolbars/preview/meta.js
  packages/toolbars/redoundo/meta.js
  packages/toolbars/refresh/meta.js
  packages/toolbars/save/meta.js
  packages/toolbars/save/src/Main.vue
  packages/toolbars/setting/meta.js
Labels: enhancement, refactor-main

#815 fea(design-core,mockServer): 引入图表物料组件
  mockServer/src/services/appinfo.json
  packages/design-core/public/mock/bundle.json
Labels: ospp-2024

#804 feat: Right Sidebar Menu and Layout Settings
  packages/controller/src/useLayout.js
  packages/design-core/config/plugin.js
  packages/design-core/src/App.vue
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/design-core/src/RightMenu.vue
  packages/plugins/help/src/HelpIcon.vue
  packages/toolbars/logo/src/Main.vue
Labels: enhancement, ospp-2024

#816 bump deps version
  designer-demo/package.json
  package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/template/designer/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/theme/dark/package.json
  packages/theme/light/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/vue-generator/src/templates/vue-template/templateFiles/packageJson.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/package.json
  packages/vue-generator/vite.config.js
  packages/webcomponent/package.json
Labels: ready_for_review, refactor-main

#818 fix: mock block data response data missing data attribute
  mockServer/src/services/block.js
  packages/controller/src/useResource.js
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/js/blockSetting.jsx
Labels: bug, ready_for_review

#820 fix: page or block save update breadcrumb incorrectly
  packages/controller/js/http.js
  packages/plugins/block/src/BlockSetting.vue
  packages/plugins/block/src/js/blockSetting.jsx
  packages/plugins/page/src/PageSetting.vue
  packages/toolbars/save/src/js/index.js
Labels: bug, ready_for_review

#827 fix: add block panel can't open
  packages/common/component/PluginBlockList.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/materials/src/meta/block/src/BlockPanel.vue
  packages/plugins/materials/src/meta/block/src/Main.vue
Labels: bug, refactor-main

#821 fix: add missing deps
  mockServer/package.json
  packages/engine-cli/template/designer/package.json
Labels: bug, ready_for_review, refactor-main

#828 feat(mockServer): 实现admin template
  mockServer/src/database/templates.db
Labels: ospp-2024

#798 feat(toolbars): use toolbar base component in toolbar plugins
  packages/common/component/ToolbarBase.vue
  packages/common/component/index.js
  packages/common/component/toolbar-built-in/ToolbarBaseButton.vue
  packages/common/component/toolbar-built-in/ToolbarBaseIcon.vue
  packages/design-core/index.js
  packages/layout/src/DesignToolbars.vue
  packages/layout/src/ToolbarCollapse.vue
  packages/toolbars/breadcrumb/meta.js
  packages/toolbars/breadcrumb/src/Main.vue
  packages/toolbars/clean/meta.js
  packages/toolbars/clean/package.json
  packages/toolbars/clean/src/Main.vue
  packages/toolbars/collaboration/meta.js
  packages/toolbars/collaboration/package.json
  packages/toolbars/collaboration/src/Main.vue
  packages/toolbars/fullscreen/meta.js
  packages/toolbars/fullscreen/src/Main.vue
  packages/toolbars/generate-code/meta.js
  packages/toolbars/generate-code/src/Main.vue
  packages/toolbars/lang/meta.js
  packages/toolbars/lang/package.json
  packages/toolbars/lang/src/Main.vue
  packages/toolbars/lock/meta.js
  packages/toolbars/lock/package.json
  packages/toolbars/lock/src/Main.vue
  packages/toolbars/logo/meta.js
  packages/toolbars/logo/src/Main.vue
  packages/toolbars/media/meta.js
  packages/toolbars/media/package.json
  packages/toolbars/media/src/Main.vue
  packages/toolbars/preview/meta.js
  packages/toolbars/preview/src/Main.vue
  packages/toolbars/redoundo/meta.js
  packages/toolbars/redoundo/package.json
  packages/toolbars/redoundo/src/Main.vue
  packages/toolbars/refresh/meta.js
  packages/toolbars/refresh/package.json
  packages/toolbars/refresh/src/Main.vue
  packages/toolbars/save/meta.js
  packages/toolbars/save/src/Main.vue
  packages/toolbars/setting/meta.js
  packages/toolbars/setting/package.json
  packages/toolbars/setting/src/Main.vue
Labels: refactor-main

#835 feat: labelPosition support 'auto'
  packages/common/component/ConfigItem.vue
Labels: enhancement, refactor-main

#836 chore(cli): engine-cli sync designer template
  packages/engine-cli/template/designer/registry.js
  packages/engine-cli/template/designer/src/preview.js
Labels: refactor-main

#826 feat(style): modify advance panel ui
  packages/common/component/MetaCodeEditor.vue
  packages/configurator/src/slot-configurator/SlotConfigurator.vue
  packages/configurator/src/variable-configurator/VariableConfigurator.vue
  packages/design-core/assets/add.svg
  packages/plugins/i18n/src/Main.vue
  packages/settings/events/src/commonjs/events.js
  packages/settings/events/src/components/AddEventsDialog.vue
  packages/settings/events/src/components/AdvanceConfig.vue
  packages/settings/events/src/components/BindEvents.vue
  packages/settings/events/src/components/BindEventsDialog.vue
  packages/settings/events/src/components/BindEventsDialogContent.vue
  packages/settings/events/src/components/BindEventsDialogSidebar.vue
  packages/theme/base/src/component-common.less
  packages/theme/dark/canvas.less
  packages/theme/dark/events.less
  packages/theme/light/canvas.less
  packages/theme/light/events.less
  packages/toolbars/generate-code/src/Main.vue
Labels: refactor-main

#838 fix: add style import to bundle
  packages/theme/base/vite.config.js
Labels: bug, ready_for_review, refactor-main

#839 fix: save page updateTreeData error
  packages/controller/js/http.js
Labels: bug, ready_for_review
