Repository opentiny/tiny-engine, pull requests merged in 2024-10, with the labels that each got.

#848 fix: improve the style priority of overwriting tinyvue
  packages/theme/base/src/component-common.less
Labels: bug, refactor-main

#850 feat: customized canvas entry
  packages/build/vite-config/src/vite-plugins/devAliasPlugin.js
  packages/canvas/.eslintrc.cjs
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/package.json
  packages/canvas/render/src/RenderMain.js
  packages/canvas/render/src/context.js
  packages/canvas/render/src/runner.js
  packages/canvas/vite.config.js
  packages/design-core/src/canvas/canvas.js
  packages/settings/events/src/components/BindEventsDialog.vue
  packages/toolbars/preview/src/Main.vue
  packages/toolbars/save/src/Main.vue
  packages/toolbars/save/src/js/index.js
Labels: enhancement, refactor-main

#859 fix: cli generate platform issue
  packages/engine-cli/src/commands/create.js
  packages/engine-cli/template/designer/vite.config.js
Labels: bug, ready_for_review, refactor-main

#851 fix(theme): modify collapse-item border
  packages/theme/base/src/component-common.less
Labels: refactor-main

#858 fix: catch script error
  packages/plugins/script/src/js/method.js
Labels: bug, refactor-main

#830 refactor(styles): apply new styles to props panel
  designer-demo/public/mock/bundle.json
  packages/common/component/ConfigItem.vue
  packages/common/component/MetaChildItem.vue
  packages/common/component/MetaCodeEditor.vue
  packages/common/component/MetaList.vue
  packages/common/component/MetaListItem.vue
  packages/configurator/src/array-item-configurator/ArrayItemConfigurator.vue
  packages/configurator/src/button-group-configurator/ButtonGroupConfigurator.vue
  packages/configurator/src/checkbox-configurator/CheckBoxConfigurator.vue
  packages/configurator/src/color-configurator/ColorConfigurator.vue
  packages/design-core/assets/border-all.svg
  packages/design-core/assets/border-bottom.svg
  packages/design-core/assets/border-left.svg
  packages/design-core/assets/border-right.svg
  packages/design-core/assets/border-top.svg
  packages/plugins/materials/src/js/options.js
  packages/settings/styles/src/components/border/BorderGroup.vue
  packages/settings/styles/src/components/buttons/ButtonGroup.vue
  packages/settings/styles/src/components/index.js
  packages/theme/base/src/component-common.less
Labels: ready_for_review, refactor-main

#837 fix: change namespace 2 export module
  packages/vue-generator/src/generator/generateApp.js
  packages/vue-generator/src/index.d.ts
  packages/vue-generator/src/plugins/formatCodePlugin.js
  packages/vue-generator/src/plugins/genBlockPlugin.js
  packages/vue-generator/src/plugins/genDataSourcePlugin.js
  packages/vue-generator/src/plugins/genDependenciesPlugin.js
  packages/vue-generator/src/plugins/genGlobalState.js
  packages/vue-generator/src/plugins/genI18nPlugin.js
  packages/vue-generator/src/plugins/genPagePlugin.js
  packages/vue-generator/src/plugins/genRouterPlugin.js
  packages/vue-generator/src/plugins/genUtilsPlugin.js
  packages/vue-generator/src/plugins/parseSchemaPlugin.js
Labels: bug, ready_for_review

#823 feat: remove generate code from mock server
  mockServer/package.json
  mockServer/src/services/schema2code.js
Labels: enhancement, refactor-main

#862 fix: preview error
  packages/design-core/src/preview/src/Toolbar.vue
Labels: bug, refactor-main

#797 Feat(page): Add exporting components and APIs for page component to support page template extension (alpha version)
  packages/common/component/MetaListItem.vue
  packages/design-core/index.js
  packages/plugins/page/index.js
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageFolderSetting.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/page/src/composable/usePage.js
Labels: refactor-main

#852 fix: blockName regexp incorrect
  packages/controller/js/verification.js
Labels: ready_for_review

#847 fix: datasource remote result could not reshow again after edit
  packages/plugins/datasource/src/DataSourceRemoteDataResult.vue
Labels: bug, ready_for_review

#780 Ospp 2024/feat schema render
  packages/plugins/robot/docs/README.md
  packages/plugins/robot/docs/image/key_process1.png
  packages/plugins/robot/docs/image/key_process2.png
  packages/plugins/robot/docs/image/robot_process1.png
  packages/plugins/robot/docs/image/robot_process2.png
  packages/plugins/robot/docs/image/robot_process3.png
  packages/plugins/robot/src/ContentDialog.vue
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/TokenDialog.vue
  packages/plugins/robot/src/js/useDialogContent.js
Labels: ospp-2024

#866 feat: Editor full screen with title, close button, and examples
  packages/common/component/MonacoEditor.vue
  packages/plugins/state/src/CreateStore.vue
  packages/plugins/state/src/CreateVariable.vue
  packages/plugins/state/src/Main.vue
  packages/plugins/state/src/StateFullscreenHead.vue
  packages/plugins/state/src/StateTips.vue
Labels: enhancement, refactor-main

#868 refactor(styles): rewrite block styles
  packages/common/component/BindI18n.vue
  packages/common/component/BlockDescription.vue
  packages/common/component/BlockLinkField.vue
  packages/common/component/ConfigItem.vue
  packages/common/component/LifeCycles.vue
  packages/common/component/MetaListItem.vue
  packages/common/component/PluginBlockItemImg.vue
  packages/common/component/PluginBlockList.vue
  packages/design-core/assets/block-add-prop.svg
  packages/design-core/assets/block-bind-prop.svg
  packages/design-core/assets/text-copy-page.svg
  packages/plugins/block/src/BlockGroupArrange.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/composable/useBlock.js
  packages/plugins/materials/src/meta/block/src/BlockGroupArrange.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupTransfer.vue
  packages/plugins/materials/src/meta/block/src/BlockList.vue
  packages/plugins/materials/src/meta/block/src/BlockPanel.vue
  packages/plugins/materials/src/meta/block/src/BlockVersionSelect.vue
  packages/plugins/page/src/PageFolderSetting.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/page/src/PageTree.vue
  packages/settings/props/src/Main.vue
Labels: refactor-main

#702 feat: editorInfo migrate to globalService
  designer-demo/registry.js
  designer-demo/src/main.js
  packages/common/composable/defaultGlobalService.js
  packages/common/composable/index.js
  packages/common/composable/useApp.js
  packages/common/composable/useEditorInfo.js
  packages/common/js/canvas.js
  packages/configurator/src/collection-configurator/CollectionConfigurator.vue
  packages/configurator/src/variable-configurator/VariableConfigurator.vue
  packages/design-core/index.js
  packages/design-core/src/App.vue
  packages/design-core/src/init.js
  packages/design-core/src/preview/src/previewApp.vue
  packages/engine-cli/template/designer/registry.js
  packages/engine-cli/template/designer/src/main.js
  packages/plugins/block/src/BlockConfig.vue
  packages/plugins/block/src/composable/useBlock.js
  packages/plugins/block/src/js/blockSetting.jsx
  packages/plugins/bridge/src/BridgeSetting.vue
  packages/plugins/bridge/src/js/resource.js
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceGlobalDataHandler.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/composable/useResource.js
  packages/plugins/materials/src/meta/block/src/BlockDetail.vue
  packages/plugins/materials/src/meta/block/src/BlockGroup.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
  packages/plugins/materials/src/meta/block/src/BlockList.vue
  packages/plugins/materials/src/meta/block/src/BlockPanel.vue
  packages/plugins/materials/src/meta/block/src/http.js
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageFolderSetting.vue
  packages/plugins/page/src/PageHistory.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/robot/src/js/robotSetting.js
  packages/plugins/state/src/Main.vue
  packages/register/src/common.js
  packages/register/src/constants.js
  packages/register/src/hooks.js
  packages/register/src/index.js
  packages/register/src/service.js
  packages/register/src/useState.js
  packages/register/test/useState.test.js
  packages/toolbars/generate-code/src/Main.vue
  packages/toolbars/logo/src/AppList.vue
  packages/toolbars/logo/src/Main.vue
Labels: enhancement, refactor-main

#842 optimize：Cj subsequent optimization
  packages/common/component/PluginPanel.vue
  packages/controller/src/useLayout.js
  packages/design-core/src/DesignCanvas.vue
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
Labels: ospp-2024

#843 doc：Cj doc edit使用说明书文档编写
  packages/design-core/docs/images/01.png
  packages/design-core/docs/images/02.png
  packages/design-core/docs/images/03.png
  packages/design-core/docs/images/04.png
  packages/design-core/docs/images/05.png
  packages/design-core/docs/images/06.png
  packages/design-core/docs/images/07.png
  packages/design-core/docs/images/08.png
  packages/design-core/docs/images/09.png
  packages/design-core/docs/images/10.png
  packages/design-core/docs/images/11.png
  packages/design-core/docs/images/12.png
  packages/design-core/docs/images/13.png
  packages/design-core/docs/images/14.png
  packages/design-core/docs/images/15.png
  packages/design-core/docs/images/16.png
  packages/design-core/docs/images/17.png
  packages/design-core/docs/images/18.png
  packages/design-core/docs/images/19.png
  packages/design-core/docs/images/20.png
  packages/design-core/docs/images/21.png
  packages/design-core/docs/产品说明书.md
Labels: ospp-2024

#833 feat(plugins): 功能优化与问题修复
  packages/controller/src/usePage.js
  packages/controller/src/useTemplate.js
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/template/readme.md
  packages/plugins/template/src/TemplateTree.vue
Labels: ospp-2024

#887 fix(refactor/styles): fix property panel styles and common styles
  packages/common/component/ConfigItem.vue
  packages/common/component/MetaChildItem.vue
  packages/common/component/MetaCodeEditor.vue
  packages/configurator/src/js-slot-configurator/JsSlotConfigurator.vue
  packages/configurator/src/slider-configurator/SliderConfigurator.vue
  packages/configurator/src/slot-configurator/SlotConfigurator.vue
  packages/design-core/assets/empty-action.svg
  packages/settings/events/src/components/AdvanceConfig.vue
  packages/settings/events/src/components/BindEvents.vue
  packages/settings/events/src/components/BindEventsDialog.vue
  packages/settings/events/src/components/BindEventsDialogContent.vue
  packages/settings/events/src/components/BindEventsDialogSidebar.vue
  packages/settings/styles/src/components/background/BackgroundGroup.vue
  packages/settings/styles/src/components/border/BorderGroup.vue
  packages/settings/styles/src/components/effects/EffectGroup.vue
  packages/settings/styles/src/components/size/SizeGroup.vue
  packages/settings/styles/src/components/typography/TypographyGroup.vue
  packages/theme/base/src/base.less
  packages/theme/base/src/common.less
  packages/theme/base/src/component-common.less
  packages/theme/base/src/page/base-config-page.less
  packages/theme/dark/variable.less
  packages/theme/light/variable.less
Labels: refactor-main

#890 fix(page-setting): Use the meta options injection method to each component of the page module.
  packages/plugins/page/index.js
  packages/plugins/page/src/PageSetting.vue
Labels: refactor-main

#880 fix: parse template name error
  packages/vue-generator/src/plugins/genTemplatePlugin.js
  packages/vue-generator/src/templates/vue-template/index.js
Labels: bug

#841 fix: element-plus 物料适配问题修复与文档补充
  docs/element plus.md
  docs/images/01.png
  docs/images/02bundle.png
  docs/images/03.png
  docs/images/04.png
  docs/images/05.png
  docs/images/06.png
  docs/images/07.png
  docs/images/08.png
  packages/design-core/public/mock/bundle.json
Labels: bug, ospp-2024
