Repository opentiny/tiny-engine, pull requests merged in 2024-08, with the labels that each got.

#722 fix(bridge):Bridge插件的二级增页适应拖拽功能
  packages/plugins/bridge/src/BridgeSetting.vue
Labels: ospp-2024

#723 fix(Data):Data插件的二级增页适应拖拽功能
  packages/plugins/data/src/Main.vue
Labels: ospp-2024

#705 feat(design-core,controller,plugins,mockServer): 实现模板类别和模板的CRUD
  mockServer/src/database/templates.db
  mockServer/src/routes/main-routes.js
  mockServer/src/services/mockService.js
  mockServer/src/services/templates.js
  packages/controller/src/index.js
  packages/controller/src/useResource.js
  packages/controller/src/useTemplate.js
  packages/design-core/assets/add-template.svg
  packages/design-core/assets/plugin-icon-template.svg
  packages/design-core/config/addons.js
  packages/design-core/package.json
  packages/plugins/template/assets/test.png
  packages/plugins/template/index.js
  packages/plugins/template/mock/test.js
  packages/plugins/template/package.json
  packages/plugins/template/readme.md
  packages/plugins/template/src/Main.vue
  packages/plugins/template/src/TemplateGeneral.vue
  packages/plugins/template/src/TemplateSetting.vue
  packages/plugins/template/src/TemplateTree.vue
  packages/plugins/template/src/http.js
  packages/plugins/template/test/test.js
  packages/plugins/template/vite.config.js
Labels: ospp-2024

#703 feat(download-code): support download zip for not support browsers
  packages/design-core/package.json
  packages/utils/package.json
  packages/utils/src/fs/fszip.js
  packages/utils/src/fs/index.js
Labels: enhancement, ready_for_review

#725 refactor: Plugins can be adapted to both the left and right side panels
  packages/controller/src/useLayout.js
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/settings/events/index.js
  packages/settings/events/src/Main.vue
  packages/settings/props/index.js
  packages/settings/props/src/Main.vue
  packages/settings/styles/index.js
  packages/settings/styles/src/Main.vue
Labels: ospp-2024

#730 fix: abaolute canvas init inlineStyle should be string
  packages/canvas/src/components/container/container.js
Labels: ready_for_review

#724 feat: Introduce AI dialog model "Kimi"
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/TokenDialog.vue
  packages/plugins/robot/src/js/robotSetting.js
Labels: ospp-2024

#732 refactor:The plugin width is persisted using vueuse.
  mockServer/assets/css/0.1.20/index.css
  package.json
  packages/common/component/PluginPanel.vue
  packages/controller/src/useLayout.js
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/plugins/bridge/src/BridgeSetting.vue
  packages/plugins/data/src/Main.vue
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceGlobalDataHandler.vue
  packages/plugins/datasource/src/DataSourceRecordList.vue
  packages/plugins/datasource/src/DataSourceRemotePanel.vue
  packages/plugins/page/src/PageFolderSetting.vue
  packages/plugins/page/src/PageSetting.vue
  packages/settings/events/src/Main.vue
Labels: ospp-2024

#737 feat(template): 模板搜索，模板类别默认有folder icon
  packages/plugins/template/src/TemplateGeneral.vue
  packages/plugins/template/src/TemplateTree.vue
Labels: ospp-2024

#738 refactor: The plugin fixed state is persisted using vueuse.
  packages/controller/src/useLayout.js
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
Labels: ospp-2024

#750 feat(cdn): change cdn from onmicrosoft to unpkg
  packages/blockToWebComponentTemplate/vite.config.js
  packages/design-core/.env.alpha
  packages/design-core/.env.development
  packages/design-core/.env.prod
  packages/design-core/public/mock/bundle.json
Labels: ready_for_review

#742 feat(plugins,toolbars,utils,controller): 添加区块内容到template
  mockServer/src/database/pages.db
  mockServer/src/database/templates.db
  packages/common/component/MetaBindVariable.vue
  packages/controller/js/http.js
  packages/controller/src/useBlock.js
  packages/controller/src/useBreadcrumb.js
  packages/controller/src/useCanvas.js
  packages/controller/src/useEditorInfo.js
  packages/controller/src/useHistory.js
  packages/controller/src/useLayout.js
  packages/controller/src/useResource.js
  packages/controller/src/useSaveLocal.js
  packages/controller/src/useTemplateCanvas.js
  packages/design-core/src/DesignCanvas.vue
  packages/plugins/block/src/js/blockSetting.jsx
  packages/plugins/data/src/Main.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/script/src/js/method.js
  packages/plugins/template/src/TemplateSetting.vue
  packages/plugins/template/src/TemplateTree.vue
  packages/plugins/template/src/http.js
  packages/toolbars/save/src/Main.vue
  packages/toolbars/save/src/js/index.js
  packages/utils/src/constants/index.js
Labels: ospp-2024

#492 fix: 隐藏画布根节点的包裹元素的操作选项
  packages/canvas/src/components/container/CanvasAction.vue
  packages/canvas/src/components/render/RenderMain.js
Labels: bug, ready_for_review

#549 fix(script): translate log
  scripts/buildMaterials.mjs
  scripts/connection.mjs
  scripts/splitMaterials.mjs
Labels: ready_for_review

#752 refactor: Refactor width persistence
  packages/controller/src/useLayout.js
  packages/design-core/src/App.vue
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/plugins/block/index.js
  packages/plugins/bridge/index.js
  packages/plugins/data/index.js
  packages/plugins/datasource/index.js
  packages/plugins/help/index.js
  packages/plugins/i18n/index.js
  packages/plugins/materials/index.js
  packages/plugins/page/index.js
  packages/plugins/robot/index.js
  packages/plugins/schema/index.js
  packages/plugins/script/index.js
  packages/plugins/tree/index.js
  packages/settings/events/index.js
  packages/settings/props/index.js
  packages/settings/styles/index.js
Labels: ospp-2024

#773 fix: width of i18n plugin is not enough
  packages/layout/src/DesignPlugins.vue
Labels: bug, refactor-main

#655 fix: add packages desc for lerna
  packages/engine-cli/template/designer/package.json
Labels: bug, ready_for_review

#766 refactor: The plugin layout state is persisted using vueuse
  packages/controller/src/useLayout.js
  packages/design-core/config/addons.js
  packages/design-core/config/plugin.js
  packages/design-core/src/App.vue
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/plugins/block/index.js
  packages/plugins/bridge/index.js
  packages/plugins/data/index.js
  packages/plugins/datasource/index.js
  packages/plugins/help/index.js
  packages/plugins/i18n/index.js
  packages/plugins/materials/index.js
  packages/plugins/page/index.js
  packages/plugins/robot/index.js
  packages/plugins/schema/index.js
  packages/plugins/script/index.js
  packages/plugins/tree/index.js
  packages/settings/events/index.js
  packages/settings/props/index.js
  packages/settings/styles/index.js
Labels: ospp-2024
