Repository opentiny/tiny-engine, pull requests merged in 2024-04, with the labels that each got.

#367 fix(readme-build): 添加Readme中构建产物所在文件夹信息
  README.md
  README.zh-CN.md
Labels: ready_for_review

#340 fix(scrollbar): fix robot plugin scrollbar hide almost all scrollbar bug
  packages/plugins/robot/src/Main.vue
  packages/settings/design/src/App.vue
  packages/theme/common/base.less
  packages/theme/dark/index.less
  packages/theme/dark/scrollbar.less
  packages/theme/light/index.less
  packages/theme/light/scrollbar.less
Labels: bug, ready_for_review

#381 fix(errorMonitor): add config for errormonitor
  packages/controller/js/http.js
  packages/controller/js/monitor.js
  packages/design-core/.env.alpha
  packages/design-core/src/main.js
Labels: bug, ready_for_review, ready to merge

#380 fix(controller-environment): preserve import.meta.env variable when b…
  packages/controller/package.json
  packages/controller/vite.config.js
Labels: bug, ready_for_review, ready to merge

#391 fix(settings): fix text wrap of bind condition
  packages/settings/events/src/components/AdvanceConfig.vue
Labels: enhancement, ready_for_review, ready to merge

#399 feat:增加物料:TinyDatePicker和TinyNumeric
  mockServer/src/services/appinfo.json
  packages/design-core/public/mock/bundle.json
Labels: enhancement, ready_for_review

#395 fix(material): add buttonComponentsMap config
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
Labels: bug, ready_for_review, ready to merge

#398 fix(demo-data): 修复官方 demo 页面底部确认购买模块移动端设备宽度下被遮住的场景
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
Labels: bug, ready_for_review

#423 fix(err-monitor): stop monitoring if monitorurl not exist
  packages/controller/js/http.js
  packages/controller/js/monitor.js
Labels: bug, ready_for_review

#421 fix(chore): fix some vue warining on console
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
  packages/plugins/help/src/HelpIcon.vue
Labels: bug, ready_for_review

#420 fix(controller): build with env variable
  packages/controller/vite.config.js
Labels: bug, ready_for_review

#385 Feat provide eslint prettier modify config
  packages/canvas/vite.config.js
  packages/common/vite.config.js
  packages/controller/js/ast.js
  packages/controller/js/config-files/eslint-rule.js
  packages/controller/js/config-files/prettierrc.js
  packages/controller/js/linter.js
  packages/controller/js/worker-files/eslint.worker.js
  packages/controller/package.json
  packages/controller/vite.config.js
  packages/design-core/package.json
  packages/design-core/public/monaco-linter/eslint.worker.js
  packages/design-core/vite.config.js
  packages/toolbars/generate-vue/src/generateCode.js
  packages/vue-generator/package.json
  packages/vue-generator/src/utils/index.js
  packages/vue-generator/vite.config.js
Labels: enhancement, ready_for_review

#364 fix: 修复画布组件嵌套拖拽的问题
  packages/canvas/src/components/container/CanvasAction.vue
  packages/canvas/src/components/container/container.js
  packages/theme/dark/canvas.less
  packages/theme/light/canvas.less
Labels: bug, ready_for_review

#393 fix: 修复画布设置成自由布局后无法拖动drag-resize改变宽高的问题
  packages/canvas/src/components/container/CanvasAction.vue
Labels: bug, ready_for_review

#426 fix(canvas): wrapper runner render context initialization with function #161
  packages/canvas/src/components/render/runner.js
Labels: bug, ready_for_review

#431 fix(chore): update pr check node version
  .github/workflows/push-check.yml
Labels: ready_for_review, ready to merge

#346 fix(dsl-page):修复本地运行中对于props属性引用utils出码报错的问题
  packages/vue-generator/src/generator/page.js
Labels: bug, ready_for_review, ready to merge

#434 fix(plugin-dataSource): 修复数据源面板新增时未校验名称的重复性
  packages/plugins/datasource/src/DataSourceField.vue
  packages/plugins/datasource/src/DataSourceFieldForm.vue
Labels: bug, ready_for_review, ready to merge

#428 fix: 修改滚动到节点的逻辑，适配超宽超高组件
  packages/canvas/src/components/container/container.js
Labels: bug, ready_for_review, ready to merge

#413 fix(data-source): on configuring static data panel, the batch delete button should horizontally aligned.
  packages/plugins/datasource/src/DataSourceRecordList.vue
Labels: bug, ready_for_review

#433 (style-position)修复样式定位reset后未恢复默认值
  packages/settings/styles/src/js/parser.js
Labels: bug, ready_for_review, ready to merge

#445 fix(chore): fix vue version of 3.4.24 caught tiny-select component error
  packages/design-core/package.json
  packages/design-core/vite.config.js
Labels: bug, ready_for_review

#452 修复918.json mock数据不一致问题
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
Labels: bug, ready_for_review, ready to merge

#447 新建区块弹出框点击遮罩层会关闭
  packages/common/component/SaveNewBlock.vue
Labels: ready_for_review, ready to merge
