Repository opentiny/tiny-engine, pull requests merged in 2024-12, with the labels that each got.

#918 feat/buildin com mjs format
  packages/builtinComponent/package.json
  packages/builtinComponent/vite.config.js
Labels: ready_for_review, refactor-main

#921 fix: sync material to cli
  designer-demo/public/mock/bundle.json
  packages/engine-cli/template/designer/public/mock/bundle.json
Labels: bug, refactor-main

#926 feat(theme/baseVariable): change base variable and common variable
  designer-demo/src/configurators/MyInputConfigurator.vue
  packages/canvas/container/src/components/CanvasAction.vue
  packages/canvas/container/src/components/CanvasDivider.vue
  packages/canvas/container/src/components/CanvasResizeBorder.vue
  packages/canvas/container/src/components/shortCutPopover.vue
  packages/canvas/layout/src/CanvasLayout.vue
  packages/common/component/SearchEmpty.vue
  packages/settings/styles/src/components/inputs/ResetButton.vue
  packages/theme/base/src/base.less
  packages/theme/base/src/common.less
  packages/theme/base/src/component-common.less
  packages/theme/base/src/page/base-config-page.less
  packages/theme/dark/canvas.less
  packages/theme/dark/setting-style.less
  packages/theme/light/canvas.less
  packages/theme/light/setting-style.less
Labels: refactor-main

#929 fix: fix exportName mismatch
  designer-demo/public/mock/bundle.json
  packages/engine-cli/template/designer/public/mock/bundle.json
Labels: bug, refactor-main

#930 fix: state & globalState getter
  packages/canvas/render/src/RenderMain.js
  packages/plugins/state/src/CreateVariable.vue
Labels: bug, ready_for_review, refactor-main

#914 feat: update block filters UI in materials
  packages/plugins/materials/src/meta/block/src/BlockGroupArrange.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupFilters.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
  packages/theme/base/src/component-common.less
Labels: enhancement, refactor-main

#934 v2.0.0
  designer-demo/package.json
  mockServer/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/theme/dark/package.json
  packages/theme/light/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: refactor-main

#919 fix: slot should extra params
  packages/vue-generator/src/generator/vue/sfc/genSetupSFC.js
  packages/vue-generator/src/generator/vue/sfc/generateTemplate.js
  packages/vue-generator/test/testcases/sfc/slotParams/block.schema.json
  packages/vue-generator/test/testcases/sfc/slotParams/expected/slotParamsBlock.vue
  packages/vue-generator/test/testcases/sfc/slotParams/expected/slotParamsPage.vue
  packages/vue-generator/test/testcases/sfc/slotParams/page.schema.json
  packages/vue-generator/test/testcases/sfc/slotParams/slotParams.test.js
Labels: bug, ready_for_review, refactor-main

#923 feat: support checking all blocks in material add block panel
  packages/common/component/PluginBlockList.vue
  packages/common/component/SelectAll.vue
  packages/common/component/index.js
  packages/plugins/block/src/composable/useBlock.js
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupTransfer.vue
  packages/plugins/materials/src/meta/block/src/BlockList.vue
  packages/theme/base/src/component-common.less
Labels: enhancement, refactor-main

#925 fix: optimize bind-i18n styles
  packages/common/component/BindI18n.vue
  packages/common/component/I18nInput.vue
Labels: bug, refactor-main

#924 Fix/styles review: resolve style-panel/media/grid-column-panel styles reviews
  designer-demo/public/mock/bundle.json
  packages/common/component/ConfigItem.vue
  packages/common/component/MetaCodeEditor.vue
  packages/common/component/MetaListItem.vue
  packages/configurator/src/js-slot-configurator/JsSlotConfigurator.vue
  packages/configurator/src/tabs-group-configurator/TabsGroupConfigurator.vue
  packages/design-core/assets/restart.svg
  packages/engine-cli/template/designer/public/mock/bundle.json
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/components/background/BackgroundGroup.vue
  packages/settings/styles/src/components/background/BackgroundImageGradient.vue
  packages/settings/styles/src/components/border/BorderGroup.vue
  packages/settings/styles/src/components/classNamesContainer/index.vue
  packages/settings/styles/src/components/effects/EffectGroup.vue
  packages/settings/styles/src/components/inputs/NumericSelect.vue
  packages/settings/styles/src/components/layout/FlexBox.vue
  packages/settings/styles/src/components/layout/GridBox.vue
  packages/settings/styles/src/components/layout/LayoutGroup.vue
  packages/settings/styles/src/components/position/PositionGroup.vue
  packages/settings/styles/src/components/size/SizeGroup.vue
  packages/settings/styles/src/components/spacing/SpacingGroup.vue
  packages/settings/styles/src/components/spacing/SpacingSetting.vue
  packages/settings/styles/src/components/typography/TypographyGroup.vue
  packages/theme/base/src/common.less
  packages/toolbars/media/src/Main.vue
Labels: refactor-main

#920 fix: preview should not overwrite mainFile
  packages/design-core/src/preview/src/preview/Preview.vue
Labels: bug, ready_for_review, ready to merge, refactor-main

#916 fix: Modify UI review comments
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/common/component/BlockDeployDialog.vue
  packages/common/component/LifeCycles.vue
  packages/common/component/PluginBlockList.vue
  packages/design-core/assets/plugin-icon-js.svg
  packages/layout/src/DesignPlugins.vue
  packages/layout/src/DesignSettings.vue
  packages/plugins/block/src/BlockGroupArrange.vue
  packages/plugins/block/src/BlockSetting.vue
  packages/plugins/block/src/CategoryEdit.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/SaveNewBlock.vue
  packages/plugins/bridge/src/BridgeSetting.vue
  packages/plugins/datasource/src/DataSourceField.vue
  packages/plugins/datasource/src/DataSourceRecordList.vue
  packages/plugins/datasource/src/DataSourceRemoteAutoload.vue
  packages/plugins/datasource/src/Main.vue
  packages/plugins/help/src/HelpIcon.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/meta/block/src/BlockDetail.vue
  packages/plugins/materials/src/meta/block/src/BlockList.vue
  packages/plugins/materials/src/meta/block/src/BlockVersionSelect.vue
  packages/plugins/materials/src/meta/component/src/Main.vue
  packages/plugins/materials/src/meta/layout/src/Main.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/Main.vue
  packages/plugins/state/src/CreateVariable.vue
  packages/plugins/state/src/Main.vue
  packages/settings/events/src/components/BindEvents.vue
  packages/theme/base/src/component-common.less
  packages/toolbars/clean/src/Main.vue
  packages/toolbars/setting/src/Main.vue
Labels: bug, refactor-main

#932 feat: page support nested routers
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageHome.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/Tree.vue
  packages/plugins/page/src/composable/usePage.js
Labels: enhancement

#907 feat: Support merging categories and groups
  packages/plugins/block/index.js
  packages/plugins/block/src/BlockConfig.vue
  packages/plugins/block/src/CategoryEdit.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/SaveNewBlock.vue
  packages/plugins/block/src/composable/useBlock.js
  packages/plugins/block/src/js/blockSetting.jsx
  packages/plugins/block/src/js/http.js
Labels: enhancement, refactor-main

#938 feat：UI specification adjustment
  packages/builtinComponent/index.js
  packages/builtinComponent/src/components/CanvasFlexBox.vue
  packages/builtinComponent/src/components/CanvasSection.vue
  packages/builtinComponent/src/meta/CanvasFlexBox.json
  packages/builtinComponent/src/meta/CanvasRowColContainer.json
  packages/builtinComponent/src/meta/CanvasSection.json
  packages/builtinComponent/src/meta/index.js
  packages/canvas/DesignCanvas/src/api/useCanvas.js
  packages/canvas/render/src/builtin/builtin.json
  packages/canvas/render/src/render.js
  packages/plugins/materials/index.js
  packages/plugins/materials/src/composable/useMaterial.js
  packages/plugins/page/index.js
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/page/src/composable/usePage.js
  packages/plugins/robot/src/Main.vue
  packages/settings/styles/src/components/spacing/SpacingSetting.vue
  packages/settings/styles/src/components/typography/TypographyGroup.vue
  packages/settings/styles/src/js/useStyle.js
  packages/utils/src/utils/index.js
  packages/vue-generator/src/constant/index.js
Labels: refactor-main

#885 feat: schemaDataAsync
  designer-demo/public/mock/bundle.json
  packages/canvas/DesignCanvas/README.md
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/DesignCanvas/src/api/useCanvas.js
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/container/src/components/CanvasAction.vue
  packages/canvas/container/src/container.js
  packages/canvas/container/src/keyboard.js
  packages/canvas/package.json
  packages/canvas/render/src/RenderMain.js
  packages/canvas/render/src/builtin/CanvasCollection.js
  packages/canvas/render/src/builtin/CanvasCollection.vue
  packages/canvas/render/src/context.js
  packages/canvas/render/src/render.js
  packages/common/component/BlockDeployDialog.vue
  packages/common/component/BlockLinkEvent.vue
  packages/common/component/BlockLinkField.vue
  packages/common/component/ConfigItem.vue
  packages/common/component/LifeCycles.vue
  packages/common/component/MetaListItems.vue
  packages/common/js/canvas.js
  packages/common/js/completion.js
  packages/configurator/src/collection-configurator/CollectionConfigurator.vue
  packages/configurator/src/container-configurator/ContainerConfigurator.vue
  packages/configurator/src/html-attributes-configurator/HtmlAttributesConfigurator.vue
  packages/configurator/src/html-text-configurator/HtmlTextConfigurator.vue
  packages/configurator/src/js-slot-configurator/JsSlotConfigurator.vue
  packages/configurator/src/layout-grid-configurator/LayoutGridConfigurator.vue
  packages/configurator/src/related-editor-configurator/RelatedEditorConfigurator.vue
  packages/configurator/src/slot-configurator/SlotConfigurator.vue
  packages/configurator/src/table-columns-configurator/TableColumnsConfigurator.vue
  packages/configurator/src/variable-configurator/VariableConfigurator.vue
  packages/plugins/block/src/composable/useBlock.js
  packages/plugins/bridge/src/js/resource.js
  packages/plugins/datasource/src/DataSourceGlobalDataHandler.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/datasource/src/DataSourceRecordList.vue
  packages/plugins/datasource/src/js/datasource.js
  packages/plugins/i18n/src/composable/useTranslate.js
  packages/plugins/materials/src/composable/useMaterial.js
  packages/plugins/materials/src/composable/useResource.js
  packages/plugins/schema/package.json
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/js/method.js
  packages/plugins/state/src/DataSourceList.vue
  packages/plugins/state/src/Main.vue
  packages/plugins/tree/src/Main.vue
  packages/settings/events/src/components/AdvanceConfig.vue
  packages/settings/props/src/components/Empty.vue
  packages/settings/props/src/components/modal/ModalContent.vue
  packages/settings/props/src/composable/useProperties.js
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/components/classNamesContainer/index.vue
  packages/settings/styles/src/js/useEditor.js
  packages/settings/styles/src/js/useStyle.js
  packages/toolbars/generate-code/src/Main.vue
  packages/toolbars/preview/src/Main.vue
  packages/toolbars/redoundo/src/composable/useHistory.js
  packages/toolbars/save/src/js/index.js
  packages/utils/src/constants/index.js
Labels: enhancement, refactoring, refactor-main

#906 feat: blockCompiler
  packages/block-compiler/.eslintrc.cjs
  packages/block-compiler/README.md
  packages/block-compiler/index.html
  packages/block-compiler/package.json
  packages/block-compiler/src/dev.ts
  packages/block-compiler/src/index.ts
  packages/block-compiler/src/transformJsx.ts
  packages/block-compiler/src/vite-env.d.ts
  packages/block-compiler/test/sample/BlockFileName.vue
  packages/block-compiler/test/sample/BlockHead.vue
  packages/block-compiler/test/sample/BlockMenu.vue
  packages/block-compiler/test/sample/BlockTest.vue
  packages/block-compiler/test/sample/slotModelValueTest.vue
  packages/block-compiler/tsconfig.json
  packages/block-compiler/tsconfig.node.json
  packages/block-compiler/vite.config.ts
  packages/build/vite-config/src/vite-plugins/devAliasPlugin.js
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/DesignCanvas/src/importMap.js
  packages/canvas/container/src/container.js
  packages/canvas/package.json
  packages/canvas/render/src/BlockLoadError.vue
  packages/canvas/render/src/BlockLoading.vue
  packages/canvas/render/src/RenderMain.js
  packages/canvas/render/src/lowcode.js
  packages/canvas/render/src/render.js
  packages/canvas/render/src/runner.js
  packages/canvas/render/src/supportUmdBlock.js
  packages/common/component/PluginBlockList.vue
  packages/common/component/ProgressBar.vue
  packages/common/component/index.js
  packages/common/composable/generateCode/index.js
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/importMap.json
  packages/layout/src/DesignToolbars.vue
  packages/plugins/block/src/BlockSetting.vue
  packages/plugins/block/src/js/blockSetting.jsx
  packages/plugins/block/src/js/http.js
  packages/plugins/materials/package.json
  packages/plugins/materials/src/composable/block-compile.js
  packages/plugins/materials/src/composable/useMaterial.js
  packages/plugins/materials/src/composable/useResource.js
  packages/plugins/materials/src/meta/block/src/BlockList.vue
  packages/plugins/materials/src/meta/block/src/BlockVersionSelect.vue
  packages/vue-generator/src/constant/index.js
Labels: enhancement, refactor-main

#954 feat: add pull request base branch release/*
  .github/workflows/push-check.yml
Labels: enhancement

#953 fix: chore bug fix for v2.1
  packages/canvas/DesignCanvas/src/api/useCanvas.js
  packages/canvas/render/src/render.js
  packages/plugins/materials/src/composable/block-compile.js
  packages/toolbars/clean/src/Main.vue
Labels: bug

#948 feat: page tree supports dragging
  packages/common/js/http.js
  packages/plugins/page/src/LayerLines.vue
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/Tree.vue
  packages/plugins/page/src/composable/usePage.js
  packages/vue-generator/src/plugins/parseSchemaPlugin.js
  packages/vue-generator/src/templates/vue-template/index.js
Labels: enhancement

#956 fix: resolve some schema update issue
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/DesignCanvas/src/api/useCanvas.js
  packages/canvas/container/src/components/CanvasResize.vue
  packages/plugins/schema/src/Main.vue
  packages/settings/events/src/components/AdvanceConfig.vue
Labels: bug

#957 fix: resolve warnings
  packages/common/component/MetaCodeEditor.vue
  packages/common/component/MetaListItems.vue
  packages/common/component/PluginBlockList.vue
  packages/common/component/toolbar-built-in/ToolbarBaseButton.vue
  packages/common/component/toolbar-built-in/ToolbarBaseIcon.vue
  packages/configurator/src/tabs-group-configurator/TabsGroupConfigurator.vue
  packages/layout/src/DesignSettings.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/meta/block/src/BlockGroup.vue
  packages/plugins/materials/src/meta/block/src/BlockList.vue
  packages/plugins/materials/src/meta/layout/src/Main.vue
  packages/settings/styles/src/Main.vue
  packages/settings/styles/src/components/border/BorderGroup.vue
  packages/settings/styles/src/components/inputs/NumericSelect.vue
Labels: bug

#966 Fix: preview URL
  packages/common/js/preview.js
Labels: ready_for_review, refactor-main

#968 feat: add navigation snippet
  packages/canvas/render/src/builtin/builtin.json
  packages/design-core/assets/navigation.svg
  packages/design-core/assets/navigationv.svg
  packages/design-core/assets/routerlink.svg
  packages/design-core/assets/routerview.svg
Labels: enhancement

#976 fix: time asc add i18n failed
  packages/plugins/i18n/src/Main.vue
Labels: bug

#975 fix: basePropsGroup use deepclone prevent clone array itself
  packages/plugins/materials/src/composable/useMaterial.js
Labels: bug

#972 fix: generate code accessor scenario
  packages/vue-generator/src/generator/vue/sfc/generateAttribute.js
  packages/vue-generator/test/testcases/sfc/accessor/accessor.test.js
  packages/vue-generator/test/testcases/sfc/accessor/expected/Accessor.vue
  packages/vue-generator/test/testcases/sfc/accessor/schema.json
Labels: bug

#964 fix: blockCompile get correct version
  packages/block-compiler/src/index.ts
  packages/canvas/container/src/container.js
  packages/canvas/render/src/RenderMain.js
  packages/canvas/render/src/render.js
  packages/plugins/materials/src/composable/block-compile.js
  packages/plugins/materials/src/meta/block/index.js
  packages/plugins/materials/src/meta/block/src/BlockVersionSelect.vue
Labels: bug
