Repository opentiny/tiny-engine, pull requests merged in 2024-03, with the labels that each got.

#319 fix：资源管理工具类型文字字色与设计稿不一致
  packages/plugins/bridge/src/BridgeSetting.vue
Labels: enhancement, ready_for_review

#315 bundle.json and tiny-vue.css is 404 in prod mode
  packages/design-core/config/lowcode.config.js
Labels: enhancement, ready_for_review

#320 chore(release): publish
  mockServer/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/controller/package.json
  packages/design-core/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/data/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/dark/package.json
  packages/theme/light/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-vue/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: ready_for_review, ready to merge

#332 fix(datasource): data type icon invisible #312
  packages/common/component/MetaBindVariable.vue
  packages/plugins/datasource/src/DataSourceFieldType.vue
  packages/plugins/datasource/src/config.js
Labels: bug, ready_for_review, ready to merge

#347 fix(build): 修复构建设计器产物 ref 值未转化的 bug
  package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/controller/package.json
  packages/design-core/package.json
  packages/http/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/data/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-vue/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
Labels: bug, ready_for_review

#343 fix(preview): fix preview vue-repl unsupport jsx bug
  packages/design-core/src/preview/src/preview/Preview.vue
Labels: bug, ready_for_review

#335 docs: add project name to issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: documentation, ready_for_review, ready to merge

#318 feat: 状态管理代码编辑UI优化
  packages/common/component/MonacoEditor.vue
  packages/design-core/assets/internationalization.svg
  packages/plugins/data/src/CreateStore.vue
  packages/plugins/data/src/CreateVariable.vue
  packages/plugins/data/src/DataSourceList.vue
  packages/plugins/data/src/EditorFunctionTool.vue
  packages/plugins/data/src/EditorI18nTool.vue
  packages/plugins/data/src/Main.vue
  packages/theme/dark/variable.less
  packages/theme/light/variable.less
Labels: ready_for_review

#355 fix(material): elTable formatter should be function type
  packages/design-core/public/mock/bundle.json
Labels: bug, ready_for_review, ready to merge
