Repository opentiny/tiny-engine, pull requests merged in 2024-01, with the labels that each got.

#216 feat(chore): change dependencies type to workspace:*
  packages/canvas/package.json
  packages/common/package.json
  packages/controller/package.json
  packages/design-core/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/data/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-vue/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
Labels: enhancement, ready_for_review, ready to merge

#219 chore(release): publish
  mockServer/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/controller/package.json
  packages/design-core/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/data/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/dark/package.json
  packages/theme/light/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-vue/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: ready_for_review, ready to merge

#211 fix: 修复数据源mock数据不一致
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
  scripts/buildMaterials.mjs
Labels: bug, ready_for_review, ready to merge

#228 fix：修改css文件cdn域名
  packages/design-core/canvas.html
  packages/design-core/src/preview/src/preview/srcFiles.js
  packages/design-core/src/preview/src/preview/srcFiles/app.js
Labels: ready_for_review, ready to merge

#189 fix default img can't change width and height
  packages/canvas/src/components/builtin/builtin.json
Labels: bug, ready_for_review, ready to merge

#234 fix：插件面板固定后画布未自适应
  packages/canvas/src/components/container/CanvasResize.vue
Labels: bug, ready_for_review

#237 [plugin-data] Fix state use jsfunction issue
  packages/common/component/LifeCycles.vue
  packages/common/js/completion.js
  packages/plugins/data/src/CreateVariable.vue
  packages/plugins/script/src/Main.vue
  packages/plugins/script/src/js/method.js
Labels: enhancement, ready_for_review, ready to merge

#231 fix：materials sql
  scripts/connection.mjs
Labels: bug, ready_for_review, ready to merge

#239 fix：修复资源管理工具类型切换
  packages/plugins/bridge/src/BridgeSetting.vue
Labels: bug, ready_for_review

#230 fix: 修复样式->间距->属性值设置时遮罩样式问题
  packages/common/component/PluginBlockList.vue
  packages/common/component/PluginSetting.vue
  packages/design-core/src/DesignPlugins.vue
  packages/design-core/src/DesignSettings.vue
  packages/plugins/data/src/DataSourceRightPanel.vue
  packages/plugins/data/src/Main.vue
  packages/settings/design/src/App.vue
  packages/theme/common/base.less
  packages/theme/dark/settings.less
  packages/theme/light/settings.less
Labels: bug, ready_for_review

#184 fix(styles-spacing): 增大物料设置内外边距时点击区域 #134
  packages/settings/styles/src/components/spacing/SpacingGroup.vue
Labels: bug, ready_for_review, ready to merge

#251 fix：预览引入builtin组件依赖，built组件样式文件注入js
  packages/builtinComponent/package.json
  packages/builtinComponent/vite.config.js
  packages/design-core/src/preview/src/preview/importMap.js
Labels: bug, ready_for_review

#247 fix: 修复由于物料边框引起的左侧面板右侧边缘凹凸起伏的样式问题
  packages/plugins/materials/src/component/Main.vue
Labels: bug, ready_for_review

#254 fix: 设计器构建后使用vue runtime prod build #240
  packages/design-core/vite.config.js
Labels: bug, enhancement, ready_for_review

#253 feat: js panel add jsx support
  packages/canvas/src/components/render/render.js
  packages/common/component/MetaCodeEditor.vue
  packages/common/js/ast.js
  packages/design-core/public/mock/bundle.json
Labels: enhancement, ready_for_review

#280 fix(material-panel-svg): 修复物料左侧插件面板里图标旋转的问题
  packages/plugins/materials/src/component/Main.vue
  packages/plugins/page/src/PageTree.vue
Labels: ready_for_review, ready to merge

#275 fix：组件sql语句字段校验、提示优化
  scripts/buildMaterials.mjs
  scripts/connection.mjs
  scripts/logger.mjs
Labels: ready_for_review

#272 fix：TinyTabItem、TinyBreadcrumbItem组件配置有误
  mockServer/assets/json/bundle.json
  mockServer/src/services/appinfo.json
  packages/design-core/public/mock/bundle.json
Labels: bug, ready_for_review

#246 fix: 修复画布选中框的显示层级不正确的问题
  packages/canvas/src/components/container/CanvasAction.vue
  packages/canvas/src/components/container/CanvasContainer.vue
  packages/canvas/src/components/container/container.js
  packages/design-core/src/DesignCanvas.vue
Labels: bug, ready_for_review

#276 feat: 移除前端解锁前判断权限的逻辑，适配后台解锁接口
  packages/design-core/assets/user-locked.svg
  packages/toolbars/lock/src/Main.vue
  packages/toolbars/redoundo/src/Main.vue
Labels: ready_for_review

#259 修复画布没有根元素，与vue出码、预览不一致
  packages/canvas/src/components/render/RenderMain.js
  packages/controller/src/useProperties.js
  packages/design-core/src/DesignCanvas.vue
Labels: bug, ready_for_review

#278 fix: 修改远程字段发送请求无效
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/datasource/src/DataSourceRemoteDataAdapter.vue
  packages/plugins/datasource/src/DataSourceRemoteDataResult.vue
  packages/plugins/datasource/src/DataSourceRemotePanel.vue
Labels: bug, ready_for_review

#285 fix(chore): sync vue version
  packages/blockToWebComponentTemplate/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/controller/package.json
  packages/design-core/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/data/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-vue/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: bug, ready_for_review
