Repository opentiny/tiny-engine, pull requests merged in 2025-08, with the labels that each got.

#1573 fix: monacoEditor container add flex display
  packages/common/component/MonacoEditor.vue
Labels: bug, release

#1569 fix: disable selected action toolbar text select
  packages/canvas/container/src/components/CanvasAction.vue
Labels: bug, release

#1580 chore: bug cherry-pick
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/container/src/components/CanvasAction.vue
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/usePreviewData.ts
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, chore

#1581 fix: optimize canvas options location caculate algorithm
  packages/canvas/container/src/components/CanvasAction.vue
Labels: bug, release

#1585 v2.8.0-rc.1
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/engine-cli/template/designer/public/mock/bundle.json
  packages/engine-cli/template/designer/src/composable/http/index.js
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1596 v2.8.0
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release
