Repository opentiny/tiny-engine, pull requests merged in 2025-09, with the labels that each got.

#1630 ci: config material url on gh page workflow
  .github/workflows/deploy-gh-pages.yml
  designer-demo/registry.js
Labels: ci

#1595 fix(styles): increase selector specificity to fix ColorInput padding
  packages/configurator/src/color-configurator/ColorConfigurator.vue
  packages/settings/styles/src/components/inputs/NumericSelect.vue
Labels: bug

#1631 fix: baseURL remove slash
  designer-demo/registry.js
Labels: bug

#1598 feat: add doc front-backend-docker-deployment.md
  docs/README.md
  docs/catalog.json
  docs/solutions/front-backend-docker-deployment.md
  docs/solutions/imgs/daemon.PNG
  docs/solutions/imgs/nginxcof.PNG
Labels: documentation, enhancement

#1620 chore: update gencode template deps version
  packages/vue-generator/src/templates/vue-template/templateFiles/genViteConfig.js
  packages/vue-generator/src/templates/vue-template/templateFiles/packageJson.js
Labels: chore

#1633 Feat：Adjust the AI building interface parameters and add a cancel function
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/mcp/types.ts
  packages/plugins/robot/src/mcp/utils.ts
Labels: enhancement

#1632 Feat/resources: Add Resource manager plugin & source select configurator
  designer-demo/public/mock/bundle.json
  packages/build/vite-config/src/vite-plugins/devAliasPlugin.js
  packages/canvas/render/src/builtin/builtin.json
  packages/configurator/src/index.ts
  packages/configurator/src/model-common/constants.js
  packages/configurator/src/source-select-configurator/SourceSelectConfigurator.vue
  packages/configurator/src/source-select-configurator/http.ts
  packages/design-core/assets/plugin-icon-resource.svg
  packages/design-core/package.json
  packages/design-core/re-export.js
  packages/design-core/registry.js
  packages/layout/src/defaultLayout.js
  packages/plugins/model-manager/src/Main.vue
  packages/plugins/resource/index.ts
  packages/plugins/resource/meta.js
  packages/plugins/resource/package.json
  packages/plugins/resource/src/Main.vue
  packages/plugins/resource/src/ResourceList.vue
  packages/plugins/resource/src/ResourceSetting.vue
  packages/plugins/resource/src/js/http.ts
  packages/plugins/resource/src/styles/vars.less
  packages/plugins/resource/vite.config.ts
  packages/register/src/constants.ts
Labels: enhancement

#1619 feat: add static data source
  packages/canvas/render/src/builtin/CanvasCollection.ts
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/datasource/src/DataSourceType.vue
  packages/vue-generator/src/templates/vue-template/templateFiles/src/lowcodeConfig/dataSource.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/lowcodeConfig/dataSource.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/lowcodeConfig/dataSource.js
Labels: enhancement

#1634 fix:Modify the output code of static data source
  packages/canvas/render/src/builtin/CanvasCollection.ts
Labels: bug

#1637 fix: format toolcall result
  packages/plugins/robot/src/mcp/utils.ts
Labels: bug

#1638 Feat/resources： fix resource group validator function
  packages/plugins/resource/src/ResourceSetting.vue
Labels: enhancement

#1656 fix: highlight js function fail after bind event
  packages/settings/events/src/components/BindEventsDialog.vue
Labels: bug

#1658 feat:Adjust the logic and interaction of the AI building page
  packages/common/composable/http/index.js
  packages/plugins/robot/src/BuildLoadingRenderer.vue
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/js/utils.ts
Labels: enhancement

#1660 feat:Add line chart,bar chart and pie chart components
  designer-demo/public/mock/bundle.json
  mockServer/src/mock/get/app-center/v1/apps/schema/1.json
  packages/common/js/import-map.json
Labels: enhancement
