Repository opentiny/tiny-engine, pull requests merged in 2025-06, with the labels that each got.

#1460 chore: bug cherry-pick
  packages/canvas/render/src/material-function/page-getter.ts
  packages/plugins/materials/src/composable/useResource.ts
Labels: release, chore

#1461 v2.5.1
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1449 fix: canvas drag and drop issue
  packages/canvas/DesignCanvas/src/api/useCanvas.ts
  packages/canvas/container/src/container.ts
  packages/common/component/CanvasDragItem.vue
Labels: bug, ready_for_review

#1353 chore: add demo showcase video
  packages/plugins/page/src/tools/editSpecificPage.ts
  temp-proxy-server/demoVideo/i18n增删.mov
  temp-proxy-server/demoVideo/新建页面.mov
  temp-proxy-server/demoVideo/编辑指定页面.mov
  temp-proxy-server/demoVideo/编辑指定页面并添加组件.mov
  temp-proxy-server/demoVideo/选中修改节点.mov
Labels: chore

#1477 fix: fix issue where clicking the collapse icon does not close the po…
  packages/plugins/page/src/Tree.vue
Labels: bug, release

#1481 v2.6.0
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1470 docs: update version docs
  docs/README.md
  docs/api/frontend-api/globalService-api.md
  docs/api/frontend-api/preview-api.md
  docs/catalog.json
  docs/changelog/changelog.md
  docs/changelog/v2.7-upgrade-guide.md
  docs/extension-capabilities-overview/new-registry.md
  docs/extension-capabilities-overview/registry.md
Labels: documentation

#1347 feat: del blockToWebComponentTemplate
  docs/solutions/block-construction-solution.md
  docs/solutions/block-lan-release-solution.md
  docs/solutions/block-release-solution.md
  packages/blockToWebComponentTemplate/README.md
  packages/blockToWebComponentTemplate/package.json
  packages/blockToWebComponentTemplate/src/BlockFileName.vue
  packages/blockToWebComponentTemplate/src/lib.js
  packages/blockToWebComponentTemplate/vite.config.js
Labels: documentation, enhancement

#1462 feat: remove resetPasswordToken field
  mockServer/src/assets/json/appinfo.json
  mockServer/src/database/blockCategories.db
  mockServer/src/database/blockGroups.db
  mockServer/src/database/blocks.db
  mockServer/src/database/defaultData/default.db
  mockServer/src/database/pages.db
  mockServer/src/mock/get/app-center/apps/detail/1.json
  mockServer/src/mock/get/app-center/v1/apps/schema/1.json
  mockServer/src/mock/get/platform-center/courses.json
  mockServer/src/mock/get/platform-center/user/me.json
  mockServer/src/services/block.js
  mockServer/src/services/blocks.json
  mockServer/src/services/pages.js
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/common/composable/defaultGlobalService.ts
  packages/common/js/canvas.js
  packages/plugins/block/src/composable/types.ts
  packages/plugins/materials/src/composable/types.ts
  packages/toolbars/lock/src/Main.vue
  packages/toolbars/save/src/js/index.ts
  packages/vue-generator/test/testcases/element-plus-case/mockData.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/router/index.js
  packages/vue-generator/test/testcases/generator/mockData.js
Labels: enhancement, breaking-change

#1478 fix: bind event to function will lose comment
  packages/settings/events/package.json
  packages/settings/events/src/components/BindEventsDialog.vue
Labels: bug

#1488 v2.7.0-rc.0
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: ignore-for-release

#1490 feat: The mobile phone is selected by default and preview component JSON
  mockServer/src/assets/json/appinfo.json
  mockServer/src/mock/get/app-center/v1/apps/schema/1.json
  packages/toolbars/media/src/Main.vue
Labels: enhancement

#1493 feat:Add code output configuration
  packages/toolbars/generate-code/index.ts
  packages/toolbars/generate-code/src/Main.vue
Labels: enhancement
