Repository opentiny/tiny-engine, pull requests merged in 2025-07, with the labels that each got.

#1494 fix: defineService multiple time will get error instance
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/register/src/service.ts
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: bug, release

#1501 feat(mockServer): mockserver support custom database path
  mockServer/src/database/pages.db
  mockServer/src/services/block.js
  mockServer/src/services/blockCategory.js
  mockServer/src/services/blockGroup.js
  mockServer/src/services/pages.js
  mockServer/src/tool/Common.js
Labels: enhancement

#1474 fix: add material missing fields
  designer-demo/public/mock/bundle.json
Labels: bug, release

#1506 fix: Modify After a block is deleted from a group, data is not updated.
  packages/plugins/materials/src/meta/block/src/BlockPanel.vue
Labels: bug, release

#1507 fix(datasource): fix static data button misalignment, visibility issues, delayed validation, and counter validation logic
  packages/plugins/datasource/src/DataSourceSettingRecordList.vue
Labels: bug, release

#1508 fix: Modify preview failed
  packages/common/js/preview.js
Labels: bug, release

#1511 fix: fix blockmanage http.ts post url
  packages/plugins/block/src/js/http.ts
Labels: bug

#1514 fix(block-snapshot): change the canvas selector to #app
  packages/plugins/block/src/js/blockSetting.tsx
Labels: bug, release

#1526 fix: Modify the search issue after select all blocks
  packages/common/component/SelectAll.vue
Labels: bug, release

#1529 docs: 修复文档错别字（物料包时 → 是）
  docs/ecosystem-center/ecosystem-intro.md
Labels: documentation

#1533 docs: update advanced registry available version
  docs/extension-capabilities-overview/new-registry-advanced.md
Labels: documentation

#1532 docs: 修改 README 文档，将 @opentiny/engine-cli 改成 @opentiny/tiny-engine-cli
  README.md
  README.zh-CN.md
  packages/design-core/README.md
Labels: documentation

#1534 fix: unlock page and refresh will get empty page tips
  packages/plugins/materials/src/composable/useResource.ts
Labels: bug

#1510 fix:fix buildMaterials update sqlcontent
  scripts/connection.mjs
Labels: bug

#1542 fix: url with blockId will get empty page list
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/Tree.vue
Labels: bug

#1540 feat: sync page state and global state saving behavior
  packages/plugins/state/src/Main.vue
  packages/toolbars/save/src/js/index.ts
Labels: enhancement

#1537 feat: support hide builtin material from material list
  docs/api/frontend-api/material-api.md
  packages/plugins/materials/index.ts
  packages/plugins/materials/src/composable/useMaterial.ts
  packages/plugins/materials/src/meta/component/src/Main.vue
Labels: documentation, enhancement

#1556 fix: importMapUpdateI18nHostVersion
  packages/common/js/import-map.json
Labels: bug

#1489 feat(vite-plugin-meta-comments): optimize the processing of directly executing functions. If the function is directly called, only a synchronous ctx context is generated
  packages/build/vite-plugin-meta-comments/src/transform.js
  packages/build/vite-plugin-meta-comments/src/utils.js
  packages/build/vite-plugin-meta-comments/test/expected/entry.js.output.js
  packages/build/vite-plugin-meta-comments/test/legacy/code/entry.js
  packages/build/vite-plugin-meta-comments/test/legacy/code/output.js
Labels: enhancement

#1562 chore: add breaking change tags base on template
  .github/auto-labeler.yml
Labels: ci, chore

#1566 fix: preview ancestor has folder will get plain page
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/usePreviewData.ts
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: bug, release

#1528 feat: add mcp service
  docs/extension-capabilities-tutorial/mcpService.md
  packages/canvas/DesignCanvas/index.ts
  packages/canvas/DesignCanvas/src/mcp/index.ts
  packages/canvas/DesignCanvas/src/mcp/tools/addNode.ts
  packages/canvas/DesignCanvas/src/mcp/tools/changeNodeProps.ts
  packages/canvas/DesignCanvas/src/mcp/tools/delNode.ts
  packages/canvas/DesignCanvas/src/mcp/tools/getCurrentSelectedNode.ts
  packages/canvas/DesignCanvas/src/mcp/tools/getPageSchema.ts
  packages/canvas/DesignCanvas/src/mcp/tools/index.ts
  packages/canvas/DesignCanvas/src/mcp/tools/queryNodeById.ts
  packages/canvas/DesignCanvas/src/mcp/tools/selectSpecificNode.ts
  packages/canvas/package.json
  packages/common/composable/index.ts
  packages/common/composable/mcp/index.ts
  packages/common/composable/mcp/toolUtils.ts
  packages/common/composable/mcp/type.ts
  packages/common/package.json
  packages/design-core/re-export.js
  packages/design-core/registry.js
  packages/layout/index.ts
  packages/layout/package.json
  packages/layout/src/composable/useLayout.ts
  packages/layout/src/mcp/index.ts
  packages/layout/src/mcp/tools/getAllPlugins.ts
  packages/layout/src/mcp/tools/index.ts
  packages/layout/src/mcp/tools/switchPlugin.ts
  packages/plugins/block/vite.config.ts.timestamp-1753338715254-d98b55ce9431a.mjs
  packages/plugins/i18n/package.json
  packages/plugins/i18n/src/composable/index.ts
  packages/plugins/i18n/src/composable/tools/addI18n.ts
  packages/plugins/i18n/src/composable/tools/commonSchema.ts
  packages/plugins/i18n/src/composable/tools/delI18n.ts
  packages/plugins/i18n/src/composable/tools/getI18n.ts
  packages/plugins/i18n/src/composable/tools/index.ts
  packages/plugins/i18n/src/composable/tools/updateI18n.ts
  packages/plugins/materials/index.ts
  packages/plugins/materials/package.json
  packages/plugins/materials/src/composable/useMaterial.ts
  packages/plugins/materials/src/mcp/index.ts
  packages/plugins/materials/src/mcp/tools/getComponentDetail.ts
  packages/plugins/materials/src/mcp/tools/getComponentList.ts
  packages/plugins/materials/src/mcp/tools/index.ts
  packages/plugins/page/index.ts
  packages/plugins/page/package.json
  packages/plugins/page/src/composable/usePage.ts
  packages/plugins/page/src/mcp/index.ts
  packages/plugins/page/src/mcp/tools/addPage.ts
  packages/plugins/page/src/mcp/tools/changePageBasicInfo.ts
  packages/plugins/page/src/mcp/tools/delPage.ts
  packages/plugins/page/src/mcp/tools/editSpecificPage.ts
  packages/plugins/page/src/mcp/tools/getPageDetail.ts
  packages/plugins/page/src/mcp/tools/getPageList.ts
  packages/plugins/page/src/mcp/tools/index.ts
  packages/utils/src/utils/index.ts
  packages/utils/src/utils/validateParams.ts
Labels: documentation, enhancement

#1565 fix: preview ancestor has folder will get plain page
  packages/design-core/src/preview/src/preview/usePreviewData.ts
Labels: bug
