Repository opentiny/tiny-engine, pull requests merged in 2025-01, with the labels that each got.

#981 fix:modify style
  packages/common/component/PluginSetting.vue
  packages/plugins/materials/src/meta/block/src/BlockGroup.vue
  packages/theme/base/src/component-common.less
Labels: bug

#982 fix: optimize save code button marker position
  packages/common/component/toolbar-built-in/ToolbarBaseButton.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/Main.vue
Labels: bug

#983 fix: update cli template resolve preview error
  packages/engine-cli/template/designer/package.json
  packages/engine-cli/template/designer/public/mock/bundle.json
  packages/engine-cli/template/designer/registry.js
  packages/engine-cli/template/designer/src/composable/http/Login.vue
  packages/engine-cli/template/designer/src/composable/http/index.js
  packages/engine-cli/template/designer/src/preview.js
Labels: bug

#974 feat: Adjust the routing structure to increase the name
  packages/vue-generator/src/plugins/genRouterPlugin.js
Labels: enhancement

#984 fix: block switch select property failed
  packages/settings/props/src/composable/useProperty.js
Labels: bug

#985 fix: fix app param type error when create group
  packages/plugins/block/src/js/blockSetting.jsx
Labels: bug, refactor-main

#986 fix: fix param type error when create group
  packages/plugins/block/src/js/blockSetting.jsx
Labels: bug

#971 fix: resolve block property issue
  packages/canvas/render/src/builtin/builtin.json
  packages/plugins/block/src/BlockPropertyForm.vue
Labels: bug

#987 fix: cannot publish current editing block
  packages/plugins/block/src/js/blockSetting.jsx
Labels: bug

#988 fix: preview page breadcrumb don't exist useBlock method and preview block error when type undefined
  packages/toolbars/breadcrumb/src/Main.vue
  packages/vue-generator/src/generator/vue/sfc/generateScript.js
Labels: bug

#941 fix: Modify UI review comments
  packages/common/component/BlockDeployDialog.vue
  packages/common/component/I18nInput.vue
  packages/common/component/LifeCycles.vue
  packages/common/component/MonacoEditor.vue
  packages/common/component/PluginBlockList.vue
  packages/common/component/PluginSetting.vue
  packages/common/component/SvgButton.vue
  packages/common/component/toolbar-built-in/ToolbarBaseButton.vue
  packages/layout/src/ToolbarCollapse.vue
  packages/plugins/block/src/BlockEventList.vue
  packages/plugins/block/src/BlockPropertyList.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/datasource/src/DataSourceFieldCheckRanger.vue
  packages/plugins/datasource/src/DataSourceFieldForm.vue
  packages/plugins/datasource/src/DataSourceFieldList.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/datasource/src/DataSourceRecordList.vue
  packages/plugins/datasource/src/DataSourceRemoteAutoload.vue
  packages/plugins/datasource/src/DataSourceRemoteDataAdapter.vue
  packages/plugins/datasource/src/DataSourceRemoteDataResult.vue
  packages/plugins/datasource/src/DataSourceRemoteForm.vue
  packages/plugins/datasource/src/DataSourceRemotePanel.vue
  packages/plugins/datasource/src/RemoteDataAdapterForm.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/meta/block/src/BlockGroup.vue
  packages/plugins/materials/src/meta/component/src/Main.vue
  packages/plugins/state/src/CreateStore.vue
  packages/plugins/state/src/CreateVariable.vue
  packages/plugins/state/src/DataSourceList.vue
  packages/plugins/state/src/EditorI18nTool.vue
  packages/plugins/state/src/StateTips.vue
  packages/plugins/tree/src/Main.vue
  packages/theme/base/src/component-common.less
  packages/toolbars/fullscreen/src/Main.vue
  packages/toolbars/generate-code/meta.js
  packages/toolbars/lang/src/Main.vue
  packages/toolbars/media/src/Main.vue
  packages/toolbars/save/src/Main.vue
  packages/utils/src/constants/index.js
Labels: bug, refactor-main

#943 fix:Modify panel shadow color
  packages/common/component/PluginSetting.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/Main.vue
  packages/plugins/state/src/Main.vue
  packages/theme/base/src/base.less
Labels: bug, refactor-main

#967 feat: add canvas route bar
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/container/src/components/CanvasMenu.vue
  packages/canvas/index.js
  packages/canvas/layout/src/CanvasLayout.vue
  packages/canvas/render/src/builtin/CanvasRouterLink.vue
  packages/canvas/render/src/builtin/builtin.json
  packages/canvas/route-bar/index.js
  packages/canvas/route-bar/src/CanvasRouteBar.vue
  packages/configurator/src/index.js
  packages/configurator/src/router-select-configurator/RouterSelectConfigurator.vue
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/composable/usePage.js
Labels: enhancement

#995 fix: resolve block search exceptions
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
Labels: bug, refactor-main

#1007 fix: replace RouterLink to html anchor in canvas
  packages/canvas/render/src/builtin/CanvasRouterLink.vue
  packages/canvas/render/src/builtin/builtin.json
Labels: bug

#1009 fix: resetCanvasState indirectly called in useHistory, resets the isBlock status
  packages/canvas/DesignCanvas/src/api/useCanvas.js
  packages/toolbars/redoundo/src/composable/useHistory.js
Labels: bug, refactor-main

#1015 Revert "fix: resolve block search exceptions"
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
Labels: refactor-main

#1006 fix: block list filters not clearing
  packages/plugins/materials/src/meta/block/src/BlockGroupFilters.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
Labels: bug, refactor-main

#1016 fix: pageId comparison type does not match
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/Tree.vue
Labels: bug

#958 fix: resolve the issue of dynamic component URL errors when using relative path scripts in materials.
  packages/canvas/common/src/utils.js
Labels: bug, refactor-main

#992 fix: switch page or block should clear selection
  packages/canvas/DesignCanvas/src/api/useCanvas.js
Labels: bug, refactor-main

#996 fix: optimize block code saving and publishing logic
  packages/common/component/BlockDeployDialog.vue
  packages/plugins/block/src/js/blockSetting.jsx
Labels: bug, refactor-main

#999 fix: modify the class name of the MonacoEditor component
  packages/common/component/MonacoEditor.vue
Labels: bug, refactor-main

#970 fix: shortcut operation attribute configuration internationalization and icon configuration closed abnormally
  packages/canvas/container/src/components/CanvasAction.vue
Labels: bug, refactor-main

#997 fix: state accessor defaultValue support expression #977
  packages/vue-generator/src/generator/vue/sfc/generateAttribute.js
  packages/vue-generator/test/testcases/sfc/accessor/expected/Accessor.vue
  packages/vue-generator/test/testcases/sfc/accessor/schema.json
Labels: bug, refactor-main

#1004 fix: resolve the automatic save state invalid after refresh
  packages/toolbars/save/src/Main.vue
  packages/toolbars/save/src/js/index.js
  packages/utils/src/constants/index.js
Labels: bug, refactor-main

#950 fix：i18n options format
  packages/common/component/BindI18n.vue
  packages/common/component/ConfigItem.vue
Labels: ready_for_review, refactor-main

#817 feat: generatecode support import element style
  packages/vue-generator/package.json
  packages/vue-generator/src/generator/generateApp.js
  packages/vue-generator/src/plugins/appendElePlusStylePlugin.js
  packages/vue-generator/src/plugins/index.js
  packages/vue-generator/test/testcases/element-plus-case/element-plus-case.test.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/.gitignore
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/README.md
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/index.html
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/package.json
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/App.vue
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/http/axios.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/http/config.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/http/index.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/i18n/index.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/i18n/locale.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/lowcodeConfig/bridge.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/lowcodeConfig/dataSource.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/lowcodeConfig/dataSource.json
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/lowcodeConfig/lowcode.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/lowcodeConfig/store.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/main.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/router/index.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/stores/index.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/utils.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/views/DemoPage.vue
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/vite.config.js
  packages/vue-generator/test/testcases/element-plus-case/mockData.js
Labels: enhancement, ready_for_review, refactor-main

#1005 feat: add auto publish workflow
  .github/workflows/Release.yml
Labels: enhancement, refactor-main

#1023 feat: support drag page node to root
  packages/plugins/page/src/Tree.vue
Labels: enhancement

#1028 fix: cannot select common page
  packages/configurator/src/router-select-configurator/RouterSelectConfigurator.vue
  packages/plugins/page/src/composable/usePage.js
Labels: bug

#1029 fix: common page do not support drag
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/Tree.vue
Labels: bug

#1032 fix: remove 1px blank inside page tree container
  packages/plugins/page/src/Tree.vue
Labels: bug

#1036 fix: add error handlers and fix some misspelling of word
  packages/canvas/route-bar/src/CanvasRouteBar.vue
  packages/configurator/src/router-select-configurator/RouterSelectConfigurator.vue
  packages/plugins/page/src/PageTree.vue
Labels: bug

#1035 fix: preview page nesting and adding null detection processing
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/vue-generator/src/plugins/genRouterPlugin.js
Labels: bug

#1037 fix router page review issue
  packages/canvas/container/src/components/CanvasRouterJumper.vue
  packages/canvas/render/src/RenderMain.ts
  packages/canvas/render/src/application-function/utils.ts
  packages/canvas/render/src/builtin/CanvasRouterLink.vue
  packages/canvas/render/src/builtin/CanvasRouterView.vue
  packages/canvas/render/src/canvas-function/canvas-api.ts
  packages/canvas/render/src/canvas-function/router-view-setting.ts
  packages/canvas/render/src/data-function/parser.ts
  packages/canvas/render/src/material-function/page-getter.ts
  packages/canvas/render/src/page-block-function/methods.ts
  packages/design-core/assets/navigation.svg
  packages/design-core/assets/navigationv.svg
  packages/plugins/page/src/composable/usePage.js
Labels: bug

#949 fix: The style configuration binding variable component reads the configurator configuration
  packages/canvas/common/src/utils.js
  packages/settings/styles/src/Main.vue
Labels: bug, refactor-main

#1038 feat: the blocks categories and groups merged by default
  designer-demo/registry.js
  packages/plugins/block/index.js
Labels: enhancement, refactor-main

#1040 fix: remove redundant and wrong type declaration
  packages/canvas/render/src/RenderMain.ts
  packages/canvas/render/src/canvas-function/canvas-api.ts
  packages/canvas/render/src/data-function/parser.ts
  packages/canvas/render/src/lowcode.ts
  packages/canvas/render/src/page-block-function/schema.ts
  packages/canvas/render/src/page-block-function/state.ts
Labels: bug

#1044 fix(canvas/render): fix switching between top pages in standalone view mode, cssScope not updated and entry point pageContext active error
  packages/canvas/render/src/RenderMain.ts
Labels: refactor-main

#940 feat: materials new protocol
  designer-demo/public/mock/bundle.json
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/DesignCanvas/src/importMap.js
  packages/canvas/common/src/utils.js
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/container/src/container.js
  packages/canvas/render/src/application-function/utils.ts
  packages/canvas/render/src/runner.ts
  packages/canvas/render/type.d.ts
  packages/common/js/preview.js
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/plugins/bridge/src/js/resource.js
  packages/plugins/materials/src/composable/useMaterial.js
  packages/plugins/materials/src/composable/useResource.js
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
  packages/toolbars/generate-code/src/Main.vue
  packages/vue-generator/src/plugins/genDependenciesPlugin.js
Labels: enhancement, ready_for_review, refactor-main

#1045 fix: fix the error of routing bar caused by invalid pageid
  packages/canvas/route-bar/src/CanvasRouteBar.vue
Labels: bug

#1027 feat(refactor/theme): change incorrect css variables to the common va…
  packages/common/component/BlockLinkEvent.vue
  packages/common/component/ConfigCollapse.vue
  packages/common/component/ConfigItem.vue
  packages/common/component/EmptyTip.vue
  packages/common/component/MetaCodeEditor.vue
  packages/common/component/MetaDescription.vue
  packages/common/component/MetaListActions.vue
  packages/common/component/MetaListItem.vue
  packages/common/component/MetaModal.vue
  packages/common/component/MetaModalItem.vue
  packages/common/component/MonacoEditor.vue
  packages/common/component/PluginBlockList.vue
  packages/common/component/PluginSetting.vue
  packages/common/component/ToolbarBase.vue
  packages/common/component/VideoGuide.vue
  packages/configurator/src/tabs-group-configurator/TabsGroupConfigurator.vue
  packages/design-core/src/preview/src/Toolbar.vue
  packages/layout/src/DesignPlugins.vue
  packages/layout/src/DesignToolbars.vue
  packages/layout/src/ToolbarCollapse.vue
  packages/plugins/block/src/BlockConfig.vue
  packages/plugins/block/src/BlockEventList.vue
  packages/plugins/block/src/BlockPropertyForm.vue
  packages/plugins/block/src/BlockPropertyList.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/SaveNewBlock.vue
  packages/plugins/bridge/src/BridgeSetting.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/meta/block/src/BlockDetail.vue
  packages/plugins/materials/src/meta/block/src/BlockGroup.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupArrange.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupTransfer.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupTransferPanel.vue
  packages/plugins/materials/src/meta/block/src/BlockList.vue
  packages/plugins/materials/src/meta/component/src/Main.vue
  packages/plugins/page/src/PageInputOutput.vue
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/Main.vue
  packages/plugins/state/src/CreateRemoteAPI.vue
  packages/plugins/state/src/CreateStore.vue
  packages/plugins/state/src/CreateVariable.vue
  packages/plugins/state/src/DataSourceList.vue
  packages/plugins/state/src/Main.vue
  packages/plugins/tree/src/Main.vue
  packages/plugins/tutorial/src/TutorialVideoPanel.vue
  packages/toolbars/collaboration/src/Main.vue
  packages/toolbars/generate-code/src/FileSelector.vue
  packages/toolbars/logo/src/Main.vue
  packages/toolbars/logout/src/Main.vue
  packages/toolbars/media/src/Main.vue
Labels: refactor-main

#1048 fix: update template bundle
  packages/engine-cli/template/designer/public/mock/bundle.json
Labels: bug

#1051 feat: Modify css variables
  packages/theme/base/src/base.less
  packages/theme/base/src/common.less
Labels: enhancement, refactor-main

#1049 feat(refactor/theme): change incorrect css variables to the common variables and delete theme/base.less
  packages/canvas/container/src/components/CanvasDivider.vue
  packages/common/component/PluginBlockList.vue
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageHome.vue
  packages/plugins/page/src/PageInputOutput.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/Main.vue
  packages/settings/design/src/App.vue
  packages/settings/design/src/components/PropertyCanvas.vue
  packages/settings/design/src/components/PropertyList.vue
  packages/settings/styles/src/components/background/ImageSetting.vue
  packages/settings/styles/src/components/background/RadialGradient.vue
  packages/theme/dark/base.less
  packages/theme/dark/block.less
  packages/theme/dark/bridge.less
  packages/theme/dark/events.less
  packages/theme/dark/gpt-dialog.less
  packages/theme/dark/help.less
  packages/theme/dark/i18n.less
  packages/theme/dark/index.less
  packages/theme/dark/life-cycles.less
  packages/theme/dark/materials.less
  packages/theme/dark/metaComponent.less
  packages/theme/dark/pageManage.less
  packages/theme/dark/plugin-js.less
  packages/theme/dark/toolbar.less
  packages/theme/dark/tree.less
  packages/theme/dark/tutorial.less
  packages/theme/dark/variable.less
  packages/theme/light/base.less
  packages/theme/light/block.less
  packages/theme/light/bridge.less
  packages/theme/light/events.less
  packages/theme/light/gpt-dialog.less
  packages/theme/light/help.less
  packages/theme/light/i18n.less
  packages/theme/light/index.less
  packages/theme/light/life-cycles.less
  packages/theme/light/materials.less
  packages/theme/light/metaComponent.less
  packages/theme/light/pageManage.less
  packages/theme/light/plugin-js.less
  packages/theme/light/toolbar.less
  packages/theme/light/tree.less
  packages/theme/light/tutorial.less
  packages/theme/light/variable.less
Labels: refactor-main

#1058 fix: update template bundle
  packages/engine-cli/template/designer/public/mock/bundle.json
Labels: bug, refactor-main

#1062 Fix/mock utils axios cdn link
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
Labels: ready_for_review

#1059 fix: AI chat request error
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/js/robotSetting.js
Labels: bug

#1065 feat: Module variable rectification
  packages/common/component/BlockHistoryTemplate.vue
  packages/common/component/CloseIcon.vue
  packages/common/component/ConfigItem.vue
  packages/common/component/PluginBlockList.vue
  packages/common/component/PluginPanel.vue
  packages/common/component/PluginSetting.vue
  packages/common/component/SvgButton.vue
  packages/common/component/index.js
  packages/common/component/toolbar-built-in/ToolbarBaseButton.vue
  packages/layout/src/DesignSettings.vue
  packages/plugins/block/src/BlockConfig.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/help/src/HelpIcon.vue
  packages/plugins/materials/src/meta/block/src/BlockGroup.vue
  packages/plugins/materials/src/meta/component/src/Main.vue
  packages/plugins/page/src/Tree.vue
  packages/plugins/robot/src/Main.vue
  packages/plugins/script/src/Main.vue
  packages/plugins/state/src/Main.vue
  packages/plugins/tree/src/Main.vue
  packages/settings/events/src/components/AdvanceConfig.vue
  packages/settings/events/src/components/BindEvents.vue
  packages/settings/events/src/components/BindEventsDialogContent.vue
  packages/settings/events/src/components/BindEventsDialogSidebar.vue
  packages/theme/base/src/component-common.less
  packages/theme/dark/block.less
  packages/theme/dark/bridge.less
  packages/theme/dark/events.less
  packages/theme/dark/gpt-dialog.less
  packages/theme/dark/help.less
  packages/theme/dark/i18n.less
  packages/theme/dark/life-cycles.less
  packages/theme/dark/materials.less
  packages/theme/dark/metaComponent.less
  packages/theme/dark/pageManage.less
  packages/theme/dark/plugin-js.less
  packages/theme/dark/settings.less
  packages/theme/dark/toolbar.less
  packages/theme/dark/tree.less
  packages/theme/dark/variable.less
  packages/theme/light/block.less
  packages/theme/light/bridge.less
  packages/theme/light/events.less
  packages/theme/light/gpt-dialog.less
  packages/theme/light/help.less
  packages/theme/light/i18n.less
  packages/theme/light/life-cycles.less
  packages/theme/light/materials.less
  packages/theme/light/metaComponent.less
  packages/theme/light/pageManage.less
  packages/theme/light/plugin-js.less
  packages/theme/light/settings.less
  packages/theme/light/toolbar.less
  packages/theme/light/tree.less
  packages/theme/light/variable.less
Labels: enhancement, refactor-main

#1068 fix: Delete prompt box
  packages/plugins/help/src/HelpIcon.vue
Labels: bug

#1069 fix: parent form field in page settings do not display
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/composable/usePage.js
Labels: bug

#1079 fix: preview failure
  packages/configurator/src/radio-group-configurator/RadioGroupConfigurator.vue
  packages/design-core/src/preview/src/preview/importMap.json
Labels: bug

#1082 fix: data source type select and display exception
  packages/plugins/datasource/src/DataSourceType.vue
Labels: bug
