Repository opentiny/tiny-engine, pull requests merged in 2025-05, with the labels that each got.

#1354 fix: add path deps
  packages/build/vite-config/package.json
Labels: bug, release

#1355 v2.5.0-rc.1
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1357 fix: remove the throw error message statement
  packages/plugins/i18n/src/composable/useTranslate.ts
Labels: bug

#1358 fix: remove the throw error message statement
  packages/plugins/i18n/src/composable/useTranslate.ts
Labels: bug, release

#1360 v2.5.0-rc.2
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1364 fix: escape vite parse import.meta.env var on build phrase
  docs/api/frontend-api/preview-api.md
Labels: bug, documentation

#1361 fix: switch to new page failed after copy page
  packages/plugins/page/src/PageSetting.vue
Labels: bug, release

#1374 v2.5.0-rc.3
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1378 fix: normalize path to support window
  packages/build/vite-config/src/vite-plugins/cdnCopyPlugin.js
Labels: bug, release

#1379 v2.5.0-rc.4
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1377 feat: add meta comment unit test
  packages/build/vite-plugin-meta-comments/.gitignore
  packages/build/vite-plugin-meta-comments/package.json
  packages/build/vite-plugin-meta-comments/src/transform.js
  packages/build/vite-plugin-meta-comments/test/expected/arrow-func.js.output.js
  packages/build/vite-plugin-meta-comments/test/expected/entry.js.output.js
  packages/build/vite-plugin-meta-comments/test/expected/function-expr.js.output.js
  packages/build/vite-plugin-meta-comments/test/expected/meta-service.js.output.js
  packages/build/vite-plugin-meta-comments/test/expected/meta-service.vue.output.vue
  packages/build/vite-plugin-meta-comments/test/expected/script-setup.vue.output.vue
  packages/build/vite-plugin-meta-comments/test/expected/vue-hooks.js.output.js
  packages/build/vite-plugin-meta-comments/test/legacy/code/entry.js
  packages/build/vite-plugin-meta-comments/test/legacy/code/output.js
  packages/build/vite-plugin-meta-comments/test/legacy/index.js
  packages/build/vite-plugin-meta-comments/test/legacy/meta.js
  packages/build/vite-plugin-meta-comments/test/transform-sfc.test.js
  packages/build/vite-plugin-meta-comments/test/transform.test.js
  packages/build/vite-plugin-meta-comments/test/utils.test.js
  packages/build/vite-plugin-meta-comments/vitest.config.js
Labels: enhancement

#1373 fix: added plugins are not displayed
  packages/layout/src/composable/useLayout.ts
Labels: bug, release

#1371 fix: Modify the page to save console error
  packages/plugins/page/src/PageGeneral.vue
Labels: bug, release

#1365 fix: copy pop-up modal logic displays abnormally
  packages/plugins/page/src/PageSetting.vue
  packages/plugins/page/src/composable/usePage.ts
  packages/toolbars/save/src/js/index.ts
Labels: bug, release

#1388 v2.5.0-rc.5
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1380 feat: add sourcemap for all plugins
  packages/block-compiler/vite.config.ts
  packages/builtinComponent/vite.config.ts
  packages/canvas/vite.config.ts
  packages/common/vite.config.ts
  packages/configurator/vite.config.ts
  packages/i18n/vite.config.ts
  packages/layout/vite.config.ts
  packages/plugins/i18n/vite.config.ts
  packages/plugins/materials/vite.config.ts
  packages/plugins/page/vite.config.ts
  packages/plugins/robot/vite.config.ts
  packages/plugins/schema/vite.config.ts
  packages/plugins/script/vite.config.ts
  packages/plugins/state/vite.config.ts
  packages/plugins/tree/vite.config.ts
  packages/plugins/tutorial/vite.config.ts
  packages/register/vite.config.ts
  packages/settings/design/vite.config.ts
  packages/settings/events/vite.config.ts
  packages/settings/panel/vite.config.ts
  packages/settings/props/vite.config.ts
  packages/settings/styles/vite.config.ts
  packages/svgs/vite.config.ts
  packages/theme/base/vite.config.ts
  packages/toolbars/breadcrumb/vite.config.ts
  packages/toolbars/clean/vite.config.ts
  packages/toolbars/collaboration/vite.config.ts
  packages/toolbars/fullscreen/vite.config.ts
  packages/toolbars/generate-code/vite.config.ts
  packages/toolbars/lang/vite.config.ts
  packages/toolbars/lock/vite.config.ts
  packages/toolbars/logo/vite.config.ts
  packages/toolbars/logout/vite.config.ts
  packages/toolbars/media/vite.config.ts
  packages/toolbars/preview/vite.config.ts
  packages/toolbars/redoundo/vite.config.ts
  packages/toolbars/refresh/vite.config.ts
  packages/toolbars/save/vite.config.ts
  packages/toolbars/setting/vite.config.ts
  packages/toolbars/themeSwitch/vite.config.ts
  packages/toolbars/view-setting/vite.config.ts
  packages/utils/vite.config.ts
  packages/webcomponent/vite.config.js
Labels: enhancement

#1329 fix: del Timeline layout setting
  designer-demo/public/mock/bundle.json
Labels: bug

#1398 fix: global style：Styling disorder
  packages/settings/styles/src/components/classNamesContainer/index.vue
Labels: bug, release

#1393 fix: switch pages when panel is fixed, panel closes
  packages/layout/src/composable/useLayout.ts
Labels: bug, release

#1375 fix: select the effect after adding containers in batches
  packages/canvas/container/src/composables/useMultiSelect.ts
Labels: bug, release

#1397 fix: delete properties
  designer-demo/public/mock/bundle.json
Labels: bug

#1401 fix: Modify numeric controls-position
  designer-demo/public/mock/bundle.json
Labels: bug

#1402 fix: Modify popeditor grid-op
  designer-demo/public/mock/bundle.json
Labels: bug

#1391 fix: remove warning infos
  packages/layout/src/DesignPlugins.vue
  packages/layout/src/DesignSettings.vue
  packages/layout/src/Main.vue
  packages/settings/props/src/Main.vue
Labels: bug

#1389 docs: update useMaterial api docs
  docs/api/frontend-api/material-api.md
  docs/extension-capabilities-overview/registry.md
Labels: documentation

#1372 feat：add document
  docs/advanced-features/canvas-shortcuts.md
  docs/advanced-features/imgs/theme-switch.gif
  docs/advanced-features/route-capabilities/imgs/preview-1.png
  docs/advanced-features/route-capabilities/imgs/preview-2.gif
  docs/advanced-features/route-capabilities/imgs/preview-3.gif
  docs/advanced-features/route-capabilities/imgs/preview-4.png
  docs/advanced-features/route-capabilities/imgs/preview-5.png
  docs/advanced-features/route-capabilities/imgs/preview-6.gif
  docs/advanced-features/route-capabilities/imgs/route-1.gif
  docs/advanced-features/route-capabilities/imgs/route-2.gif
  docs/advanced-features/route-capabilities/imgs/route-3.png
  docs/advanced-features/route-capabilities/imgs/route-4.gif
  docs/advanced-features/route-capabilities/imgs/route-5.gif
  docs/advanced-features/route-capabilities/imgs/route-6.png
  docs/advanced-features/route-capabilities/imgs/route-7.gif
  docs/advanced-features/route-capabilities/imgs/route-8.png
  docs/advanced-features/route-capabilities/imgs/route-bar-1.png
  docs/advanced-features/route-capabilities/imgs/route-bar-2.gif
  docs/advanced-features/route-capabilities/page-support-nested-route.md
  docs/advanced-features/route-capabilities/route-bar-clear-preview-page.md
  docs/advanced-features/route-capabilities/route-bar-current-page-highlight.md
  docs/advanced-features/route-capabilities/route-view-support-preview-subpage.md
  docs/advanced-features/theme-switch.md
  docs/catalog.json
  docs/extension-capabilities-tutorial/how-to-custom-theme.md
  docs/extension-capabilities-tutorial/imgs/cli-theme.png
  docs/extension-capabilities-tutorial/imgs/custom-theme.gif
  docs/extension-capabilities-tutorial/imgs/default-theme.gif
  docs/extension-capabilities-tutorial/imgs/theme-registry.png
  docs/solutions/block-construction-solution.md
  docs/solutions/canvas-communication-solution.md
  docs/solutions/imgs/new-block-construction.png
  docs/solutions/imgs/new-canvas-communication.png
  docs/solutions/imgs/origin-canvas-communication.png
  docs/solutions/imgs/original-block-construction.png
Labels: documentation, enhancement

#1395 docs: add localCDN precaution tips
  docs/solutions/import-map-local.md
Labels: documentation

#1406 fix: add document img
  docs/advanced-features/imgs/canvas-shortcuts-1.png
  docs/advanced-features/imgs/canvas-shortcuts-2.png
  docs/advanced-features/imgs/canvas-shortcuts-3.png
  docs/advanced-features/imgs/canvas-shortcuts-4.png
  docs/advanced-features/imgs/canvas-shortcuts-5.png
Labels: bug

#1411 feat: replace ui with tiny-robot
  packages/plugins/robot/index.ts
  packages/plugins/robot/package.json
  packages/plugins/robot/src/Main.vue
Labels: enhancement

#1416 fix: bump robot version resolve build error
  packages/plugins/robot/package.json
Labels: bug

#1418 feat: update vite plugins to use new API
  packages/build/vite-config/src/externalDeps.js
  packages/build/vite-config/src/vite-plugins/genImportMapOnly.js
  packages/build/vite-config/src/vite-plugins/upgradeHttpsPlugin.js
Labels: chore

#1412 chore: del redundant deps
  packages/design-core/package.json
  packages/i18n/package.json
Labels: ready_for_review, ready to merge, chore

#1422 docs: add new registry docs
  docs/extension-capabilities-overview/new-registry-advanced.md
  docs/extension-capabilities-overview/new-registry.md
  docs/extension-capabilities-overview/registry.md
Labels: documentation

#1425 refactor: optimize layout plugin
  designer-demo/registry.js
  packages/build/vite-config/package.json
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/layout/src/DesignPlugins.vue
  packages/layout/src/DesignSettings.vue
  packages/layout/src/DesignToolbars.vue
  packages/layout/src/Main.vue
  packages/layout/src/defaultLayout.js
  packages/plugins/block/meta.js
  packages/plugins/bridge/meta.js
  packages/plugins/datasource/meta.js
  packages/plugins/help/meta.js
  packages/plugins/i18n/meta.js
  packages/plugins/materials/meta.js
  packages/plugins/page/meta.js
  packages/plugins/robot/meta.js
  packages/plugins/schema/meta.js
  packages/plugins/script/meta.js
  packages/plugins/state/meta.js
  packages/plugins/tree/meta.js
  packages/plugins/tutorial/meta.js
  packages/register/src/constants.ts
  packages/settings/events/meta.js
  packages/settings/props/meta.js
  packages/settings/styles/meta.js
Labels: refactoring

#1427 docs: add new layout and upgrade docs
  docs/README.md
  docs/api/frontend-api/global-layout-api.md
  docs/api/frontend-api/imgs/platformExpend.png
  docs/api/frontend-api/imgs/showCollapseFalse.png
  docs/api/frontend-api/imgs/showCollapseTrue.png
  docs/api/frontend-api/imgs/showLineFalse.png
  docs/api/frontend-api/imgs/showLineTrue.png
  docs/catalog.json
  docs/changelog/changelog.md
  docs/changelog/v2.6-upgrade-guide.md
  docs/extension-capabilities-overview/new-registry.md
  packages/layout/src/defaultLayout.js
  packages/register/src/constants.ts
Labels: documentation

#1424 feat：replace materials icon
  designer-demo/public/mock/bundle.json
  packages/builtinComponent/src/meta/CanvasFlexBox.json
  packages/builtinComponent/src/meta/CanvasRowColContainer.json
  packages/builtinComponent/src/meta/CanvasSection.json
  packages/design-core/assets/box.svg
  packages/design-core/assets/breadcrumb.svg
  packages/design-core/assets/button.svg
  packages/design-core/assets/buttons.svg
  packages/design-core/assets/carousel.svg
  packages/design-core/assets/checkbox.svg
  packages/design-core/assets/checkboxgroup.svg
  packages/design-core/assets/checkboxs.svg
  packages/design-core/assets/collapse.svg
  packages/design-core/assets/collection.svg
  packages/design-core/assets/datepick.svg
  packages/design-core/assets/dialogbox.svg
  packages/design-core/assets/flexbox.svg
  packages/design-core/assets/form.svg
  packages/design-core/assets/fullwidthcenter.svg
  packages/design-core/assets/grid.svg
  packages/design-core/assets/h16.svg
  packages/design-core/assets/hr.svg
  packages/design-core/assets/icon.svg
  packages/design-core/assets/image.svg
  packages/design-core/assets/input.svg
  packages/design-core/assets/link.svg
  packages/design-core/assets/mutexbuttons.svg
  packages/design-core/assets/navigation.svg
  packages/design-core/assets/navigationv.svg
  packages/design-core/assets/numeric.svg
  packages/design-core/assets/pager.svg
  packages/design-core/assets/paragraph.svg
  packages/design-core/assets/popeditor.svg
  packages/design-core/assets/popover.svg
  packages/design-core/assets/radio.svg
  packages/design-core/assets/routerlink.svg
  packages/design-core/assets/routerview.svg
  packages/design-core/assets/row.svg
  packages/design-core/assets/rowcolcontainer.svg
  packages/design-core/assets/search.svg
  packages/design-core/assets/select.svg
  packages/design-core/assets/slot.svg
  packages/design-core/assets/switch.svg
  packages/design-core/assets/tabs.svg
  packages/design-core/assets/text.svg
  packages/design-core/assets/timeline.svg
  packages/design-core/assets/tooltip.svg
  packages/design-core/assets/transfer.svg
  packages/design-core/assets/tree.svg
  packages/design-core/assets/video.svg
Labels: enhancement

#1404 feat: Modify the beginner guide and help question mark prompt text
  packages/common/component/LinkButton.vue
  packages/common/component/PluginPanel.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/bridge/src/Main.vue
  packages/plugins/datasource/src/Main.vue
  packages/plugins/help/src/HelpIcon.vue
  packages/plugins/help/src/styles/vars.less
  packages/plugins/i18n/src/Main.vue
  packages/plugins/page/src/Main.vue
  packages/plugins/script/src/Main.vue
  packages/plugins/state/src/Main.vue
  packages/settings/styles/src/components/classNamesContainer/index.vue
  packages/toolbars/generate-code/src/Main.vue
  packages/toolbars/preview/src/Main.vue
Labels: enhancement

#1319 Fix:物料物块详情导入的panel API不存在，替换为可用的API名
  packages/plugins/materials/src/meta/block/src/BlockDetail.vue
Labels: bug

#1366 feat: enhance PageTree component with collapse and scroll function
  packages/design-core/assets/folder-wold.svg
  packages/design-core/assets/folder.svg
  packages/design-core/assets/page-collection.svg
  packages/design-core/assets/page.svg
  packages/plugins/page/src/LayerLines.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/Tree.vue
Labels: enhancement

#1432 fix: del cur page still request current page again caught error
  packages/canvas/render/src/material-function/page-getter.ts
Labels: bug

#1356 feat: support config pageTitle update
  docs/api/frontend-api/globalService-api.md
  packages/common/composable/defaultGlobalService.ts
  packages/register/src/service.ts
Labels: documentation, enhancement, ready_for_review

#1413 feat: add ElDatePicker Material
  designer-demo/public/mock/bundle.json
Labels: enhancement

#1434 feat: del old dsl export function
  packages/vue-generator/src/generator/index.js
  packages/vue-generator/src/index.d.ts
  packages/vue-generator/src/index.js
Labels: enhancement, ready_for_review

#1440 fix: init app without pageId cannot save page
  packages/plugins/materials/src/composable/useResource.ts
Labels: bug, ready_for_review

#1423 feat: data source modification
  packages/canvas/render/src/application-function/data-source-map.ts
  packages/common/component/PluginSetting.vue
  packages/design-core/assets/upload.svg
  packages/design-core/src/preview/src/preview/srcFiles/dataSourceMap.js
  packages/plugins/datasource/src/DataSourceField.vue
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/datasource/src/DataSourceRemoteDataAdapter.vue
  packages/plugins/datasource/src/DataSourceRemoteDataResult.vue
  packages/plugins/datasource/src/DataSourceRemoteForm.vue
  packages/plugins/datasource/src/DataSourceRemotePanel.vue
  packages/plugins/datasource/src/DataSourceRemoteParameter.vue
  packages/plugins/datasource/src/DataSourceRemoteResultMapping.vue
  packages/plugins/datasource/src/DataSourceSettingRecordList.vue
  packages/plugins/datasource/src/DataSourceSettingRemote.vue
  packages/plugins/datasource/src/DataSourceSettingRemoteResult.vue
  packages/plugins/datasource/src/DataSourceSettings.vue
  packages/plugins/datasource/src/DataSourceType.vue
  packages/plugins/datasource/src/Main.vue
  packages/plugins/datasource/src/RemoteDataAdapterForm.vue
  packages/plugins/datasource/src/styles/vars.less
  packages/theme/base/src/page/base-config-page.less
Labels: enhancement, ready_for_review
