Repository opentiny/tiny-engine, pull requests merged in 2025-02, with the labels that each got.

#1074 fix: gencode element-plus test case
  packages/vue-generator/test/testcases/element-plus-case/element-plus-case.test.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/package.json
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/public/favicon.ico
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/router/index.js
Labels: bug, refactor-main

#1073 fix: deDuplicated BuiltinComponentsMap
  packages/vue-generator/src/plugins/parseSchemaPlugin.js
  packages/vue-generator/src/utils/generateImportStatement.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/package.json
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/router/index.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/views/testCanvasRowCol.vue
  packages/vue-generator/test/testcases/generator/mockData.js
Labels: bug, refactor-main

#1075 fix: canvasDivider can't work
  packages/canvas/container/src/components/CanvasDivider.vue
  packages/canvas/container/src/components/CanvasResizeBorder.vue
Labels: bug, refactor-main

#1094 fix: update splitMaterial and buildMaterials path
  scripts/buildMaterials.mjs
  scripts/splitMaterials.mjs
Labels: bug, refactor-main

#1099 fix: injectPlaceholder compact Template Node
  packages/canvas/render/src/render.ts
Labels: bug, refactor-main

#1063 Feat add router onion skinning preview
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/render/src/RenderMain.ts
  packages/canvas/render/src/canvas-function/router-preview.ts
  packages/canvas/render/src/render.ts
  packages/common/composable/defaultGlobalService.js
Labels: refactor-main

#1103 refactor: extract URL parameter related logic to defaultGlobalService
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/common/composable/defaultGlobalService.js
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/composable/useBlock.js
  packages/plugins/materials/src/composable/useResource.js
  packages/plugins/page/src/composable/usePage.js
Labels: refactor-main

#1078 feat: variable convergence(block, i18n, bridge, datasource, help, robot)
  packages/plugins/block/index.js
  packages/plugins/block/src/BlockConfig.vue
  packages/plugins/block/src/BlockEvent.vue
  packages/plugins/block/src/BlockEventForm.vue
  packages/plugins/block/src/BlockEventList.vue
  packages/plugins/block/src/BlockGroupArrange.vue
  packages/plugins/block/src/BlockProperty.vue
  packages/plugins/block/src/BlockPropertyForm.vue
  packages/plugins/block/src/BlockPropertyList.vue
  packages/plugins/block/src/BlockSetting.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/block/src/SaveNewBlock.vue
  packages/plugins/block/src/styles/vars.less
  packages/plugins/bridge/index.js
  packages/plugins/bridge/src/BridgeManage.vue
  packages/plugins/bridge/src/BridgeSetting.vue
  packages/plugins/bridge/src/Main.vue
  packages/plugins/bridge/src/styles/vars.less
  packages/plugins/datasource/index.js
  packages/plugins/datasource/src/DataSourceField.vue
  packages/plugins/datasource/src/DataSourceFieldCheck.vue
  packages/plugins/datasource/src/DataSourceFieldCheckMultipleLine.vue
  packages/plugins/datasource/src/DataSourceFieldCheckRanger.vue
  packages/plugins/datasource/src/DataSourceFieldForm.vue
  packages/plugins/datasource/src/DataSourceFieldList.vue
  packages/plugins/datasource/src/DataSourceFieldType.vue
  packages/plugins/datasource/src/DataSourceForm.vue
  packages/plugins/datasource/src/DataSourceList.vue
  packages/plugins/datasource/src/DataSourceRecordForm.vue
  packages/plugins/datasource/src/DataSourceRecordList.vue
  packages/plugins/datasource/src/DataSourceRecordUpload.vue
  packages/plugins/datasource/src/DataSourceRemoteAutoload.vue
  packages/plugins/datasource/src/DataSourceRemoteDataAdapter.vue
  packages/plugins/datasource/src/DataSourceRemoteDataResult.vue
  packages/plugins/datasource/src/DataSourceRemoteForm.vue
  packages/plugins/datasource/src/DataSourceRemoteMapping.vue
  packages/plugins/datasource/src/DataSourceRemotePanel.vue
  packages/plugins/datasource/src/DataSourceRemoteParameter.vue
  packages/plugins/datasource/src/DataSourceTemplate.vue
  packages/plugins/datasource/src/DataSourceType.vue
  packages/plugins/datasource/src/RemoteDataAdapterForm.vue
  packages/plugins/datasource/src/styles/vars.less
  packages/plugins/help/index.js
  packages/plugins/help/src/HelpIcon.vue
  packages/plugins/help/src/styles/vars.less
  packages/plugins/i18n/index.js
  packages/plugins/i18n/src/Main.vue
  packages/plugins/i18n/src/styles/vars.less
  packages/plugins/robot/index.js
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/styles/vars.less
  packages/theme/base/src/base.less
  packages/theme/base/src/common.less
  packages/theme/base/src/component-common.less
Labels: enhancement, refactor-main

#1087 feat: variable convergence(materials, page, schema, script, state, tree, tutorial)
  packages/plugins/materials/index.js
  packages/plugins/materials/src/Main.vue
  packages/plugins/materials/src/meta/block/src/BlockDetail.vue
  packages/plugins/materials/src/meta/block/src/BlockGroup.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupArrange.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupFilters.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupSort.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupTransfer.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupTransferPanel.vue
  packages/plugins/materials/src/meta/block/src/BlockPanel.vue
  packages/plugins/materials/src/meta/block/src/BlockVersionSelect.vue
  packages/plugins/materials/src/meta/component/src/Main.vue
  packages/plugins/materials/src/styles/vars.less
  packages/plugins/page/index.js
  packages/plugins/page/src/Main.vue
  packages/plugins/page/src/PageGeneral.vue
  packages/plugins/page/src/PageHome.vue
  packages/plugins/page/src/PageInputOutput.vue
  packages/plugins/page/src/PageTree.vue
  packages/plugins/page/src/Tree.vue
  packages/plugins/page/src/styles/vars.less
  packages/plugins/schema/index.js
  packages/plugins/schema/src/Main.vue
  packages/plugins/schema/src/styles/vars.less
  packages/plugins/script/index.js
  packages/plugins/script/src/Main.vue
  packages/plugins/script/src/styles/vars.less
  packages/plugins/state/index.js
  packages/plugins/state/src/CreateRemoteAPI.vue
  packages/plugins/state/src/CreateRemoteFunction.vue
  packages/plugins/state/src/CreateStore.vue
  packages/plugins/state/src/CreateVariable.vue
  packages/plugins/state/src/DataSourceList.vue
  packages/plugins/state/src/DataSourceRightPanel.vue
  packages/plugins/state/src/EditorI18nTool.vue
  packages/plugins/state/src/Main.vue
  packages/plugins/state/src/StateFullscreenHead.vue
  packages/plugins/state/src/StateTips.vue
  packages/plugins/state/src/styles/vars.less
  packages/plugins/tree/index.js
  packages/plugins/tree/src/Main.vue
  packages/plugins/tree/src/styles/vars.less
  packages/plugins/tutorial/index.js
  packages/plugins/tutorial/src/Main.vue
  packages/plugins/tutorial/src/TutorialVideoPanel.vue
  packages/plugins/tutorial/src/styles/vars.less
Labels: enhancement, refactor-main

#1105 feat: variable convergence(configurator，canvas，preview)
  packages/canvas/breadcrumb/src/CanvasBreadcrumb.vue
  packages/canvas/canvas.html
  packages/canvas/container/src/components/CanvasAction.vue
  packages/canvas/container/src/components/CanvasDivider.vue
  packages/canvas/container/src/components/CanvasMenu.vue
  packages/canvas/container/src/components/CanvasResize.vue
  packages/canvas/container/src/components/CanvasResizeBorder.vue
  packages/canvas/container/src/components/CanvasRouterJumper.vue
  packages/canvas/container/src/components/shortCutPopover.vue
  packages/canvas/index.js
  packages/canvas/layout/src/CanvasLayout.vue
  packages/canvas/route-bar/src/CanvasRouteBar.vue
  packages/canvas/styles/vars.less
  packages/configurator/src/array-item-configurator/ArrayItemConfigurator.vue
  packages/configurator/src/button-group-configurator/ButtonGroupConfigurator.vue
  packages/configurator/src/code-list-configurator/CodeListConfigurator.vue
  packages/configurator/src/group-item-configurator/GroupItemConfigurator.vue
  packages/configurator/src/html-attributes-configurator/HtmlAttributesConfigurator.vue
  packages/configurator/src/index.js
  packages/configurator/src/input-configurator/InputConfigurator.vue
  packages/configurator/src/ip-section-configurator/IpSectionConfigurator.vue
  packages/configurator/src/js-slot-configurator/JsSlotConfigurator.vue
  packages/configurator/src/layout-grid-configurator/LayoutGridConfigurator.vue
  packages/configurator/src/number-configurator/NumberConfigurator.vue
  packages/configurator/src/radio-configurator/RadioConfigurator.vue
  packages/configurator/src/related-editor-configurator/RelatedEditorConfigurator.vue
  packages/configurator/src/router-select-configurator/RouterSelectConfigurator.vue
  packages/configurator/src/select-icon-configurator/SelectIconConfigurator.vue
  packages/configurator/src/slider-configurator/SliderConfigurator.vue
  packages/configurator/src/slot-configurator/SlotConfigurator.vue
  packages/configurator/src/styles/vars.less
  packages/configurator/src/tabs-group-configurator/TabsGroupConfigurator.vue
  packages/configurator/src/variable-configurator/VariableConfigurator.vue
  packages/design-core/src/preview/src/Toolbar.vue
  packages/design-core/src/preview/src/main.js
  packages/design-core/src/preview/src/styles/vars.less
  packages/theme/base/src/common.less
Labels: enhancement, refactor-main

#1115 fix：after setting the subpage as the homepage, it becomes the first level page
  packages/plugins/page/src/PageHome.vue
Labels: refactor-main

#1111 fix: svg color not work in preview mode
  packages/vue-generator/src/generator/vue/sfc/generateTemplate.js
Labels: bug, refactor-main

#1107 fix: Modify new page interaction
  packages/plugins/page/src/PageSetting.vue
Labels: bug, refactor-main

#1102 fix: resolve some interaction issues
  packages/canvas/render/src/application-function/utils.ts
  packages/plugins/datasource/src/DataSourceType.vue
  packages/plugins/i18n/src/Main.vue
  packages/plugins/materials/src/meta/block/src/BlockGroupPanel.vue
  packages/plugins/materials/src/meta/block/src/http.js
  packages/plugins/page/src/PageHistory.vue
Labels: bug, refactor-main

#1122 fix: add @eslint/js deps declaring
  packages/common/package.json
Labels: bug, refactor-main

#1070 feat：add theme switching plugin
  designer-demo/engine.config.js
  designer-demo/registry.js
  jsconfig.json
  packages/build/vite-config/src/vite-plugins/devAliasPlugin.js
  packages/common/component/ToolbarBase.vue
  packages/design-core/assets/cn.svg
  packages/design-core/assets/dark.svg
  packages/design-core/assets/en.svg
  packages/design-core/assets/light.svg
  packages/design-core/assets/nested-page.svg
  packages/design-core/assets/single-page.svg
  packages/design-core/index.js
  packages/design-core/package.json
  packages/design-core/src/init.js
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/engine-cli/src/commands/generateConfig.js
  packages/engine-cli/template/designer/engine.config.js
  packages/engine-cli/template/designer/registry.js
  packages/layout/index.js
  packages/layout/src/DesignToolbars.vue
  packages/layout/src/ToolbarCollapse.vue
  packages/register/src/constants.js
  packages/toolbars/preview/src/Main.vue
  packages/toolbars/themeSwitch/index.js
  packages/toolbars/themeSwitch/meta.js
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/themeSwitch/src/Main.vue
  packages/toolbars/themeSwitch/src/composable/index.js
  packages/toolbars/themeSwitch/src/styles/vars.less
  packages/toolbars/themeSwitch/vite.config.js
Labels: refactor-main

#1095 fix: adjust the preview of the current page to schema data
  packages/plugins/page/src/composable/usePage.js
  packages/toolbars/preview/src/Main.vue
Labels: bug, refactor-main

#1117 feat: RouteView support switching preview
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/container/src/components/CanvasMenu.vue
  packages/canvas/container/src/components/CanvasRouterJumper.vue
  packages/canvas/container/src/components/CanvasViewerSwitcher.vue
  packages/canvas/container/src/container.js
  packages/canvas/render/src/builtin/CanvasRouterView.vue
  packages/canvas/render/src/render.ts
  packages/common/composable/defaultGlobalService.js
  packages/plugins/page/src/composable/usePage.js
Labels: enhancement, refactor-main

#1056 fix(block): fix block group info missing when edit block & fix filed block_id is undefined when change bock version
  packages/plugins/block/src/js/blockSetting.jsx
Labels: refactor-main

#1118 feat: route bar support display preview path
  packages/canvas/route-bar/src/CanvasRouteBar.vue
Labels: enhancement, refactor-main

#1100 fix: TinyGrid slot children can not operate
  packages/canvas/DesignCanvas/src/api/useCanvas.js
Labels: bug, refactor-main

#756 feat: tinyvue grid slot generate code to template
  designer-demo/public/mock/bundle.json
  mockServer/src/assets/json/appinfo.json
  mockServer/src/mock/get/app-center/v1/apps/schema/918.json
  packages/engine-cli/template/designer/public/mock/bundle.json
  packages/vue-generator/src/generator/vue/sfc/genSetupSFC.js
  packages/vue-generator/src/generator/vue/sfc/generateTemplate.js
  packages/vue-generator/test/testcases/sfc/case01/componentsMap.json
  packages/vue-generator/test/testcases/sfc/case01/expected/FormTable.vue
  packages/vue-generator/test/testcases/sfc/slotModelValue/expected/slotModelValueTest.vue
  packages/vue-generator/test/testcases/sfc/slotModelValue/page.schema.json
Labels: enhancement, refactor-main

#1050 feat: outline tree support dragging
  packages/canvas/container/src/container.js
  packages/plugins/tree/src/DraggableTree.vue
  packages/plugins/tree/src/Main.vue
Labels: enhancement, refactor-main

#1129 fix: add prettier version ^2 to workspace resolve lint-staged error and format all codes
  .prettierrc
  mockServer/.eslintrc.js
  mockServer/build/dev-server.js
  mockServer/gulpfile.js
  mockServer/pm2.js
  mockServer/src/app.js
  mockServer/src/assets/js/1505web-components.es.js
  mockServer/src/middleware/ErrorRoutesCatch.js
  mockServer/src/routes/error-routes.js
  mockServer/src/services/app.js
  mockServer/src/services/pageSchema.js
  mockServer/src/services/pages.js
  mockServer/src/services/source.js
  mockServer/src/services/utils.js
  mockServer/src/tool/Common.js
  mockServer/test/app.test.js
  package.json
  packages/design-core/src/preview/src/constant/index.js
  packages/design-core/src/preview/src/preview/srcFiles/bridge.js
  packages/design-core/src/preview/src/preview/srcFiles/constant/index.js
  packages/design-core/src/preview/src/preview/srcFiles/dataSource.js
  packages/design-core/src/preview/src/preview/srcFiles/dataSourceMap.js
  packages/design-core/src/preview/src/preview/srcFiles/injectGlobal.js
  packages/design-core/src/preview/src/preview/srcFiles/locales.js
  packages/design-core/src/preview/src/preview/srcFiles/stores.js
  packages/design-core/src/preview/src/preview/srcFiles/storesHelper.js
  packages/design-core/src/preview/src/preview/srcFiles/utils.js
  packages/design-core/src/preview/src/previewApp.js
  packages/i18n/src/i18n.js
  packages/i18n/src/main.js
  packages/settings/design/src/assets/materials/ng-components/index.js
  packages/settings/design/src/lib.js
  packages/settings/design/src/ng-properties/index.js
  packages/settings/design/src/properties/index.js
  packages/settings/design/src/schemas/index.js
  packages/settings/styles/src/js/useEvent.js
  packages/settings/styles/src/js/useLayout.js
  packages/utils/src/index.js
  packages/webcomponent/src/defineCustomElement.js
  packages/webcomponent/src/lib.js
  scripts/copyToVscode.js
  scripts/setup.js
Labels: bug, refactor-main

#951 feat: shortcut key for saving
  packages/common/component/MonacoEditor.vue
  packages/common/component/VueMonaco.vue
  packages/plugins/schema/src/Main.vue
  packages/plugins/script/src/Main.vue
Labels: enhancement, ready_for_review, refactor-main

#1055 feat: enhance canvas foundation capabilities
  packages/canvas/DesignCanvas/src/api/useCanvas.js
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/container/src/components/CanvasAction.vue
  packages/canvas/container/src/components/CanvasMenu.vue
  packages/canvas/container/src/container.js
  packages/canvas/container/src/keyboard.js
  packages/plugins/materials/src/composable/useMaterial.js
  packages/plugins/materials/src/meta/component/src/Main.vue
  packages/plugins/materials/src/meta/layout/src/Main.vue
Labels: enhancement, refactor-main

#1141 fix: add slots fail
  packages/canvas/DesignCanvas/src/api/useCanvas.js
Labels: bug

#1140 fix: add slots fail
  packages/canvas/DesignCanvas/src/api/useCanvas.js
Labels: bug

#1149 fix: header content lost when dragging from outline tree
  packages/plugins/tree/src/Main.vue
Labels: bug

#1150 fix: insert logic and multi node insert issue
  packages/canvas/DesignCanvas/src/api/useCanvas.js
  packages/canvas/container/src/container.js
  packages/canvas/container/src/keyboard.js
  packages/canvas/container/src/utils.js
Labels: bug

#1119 feat: add API Token
  packages/plugins/robot/src/Main.vue
  packages/plugins/robot/src/RobotSettingPopover.vue
Labels: enhancement
