Repository opentiny/tiny-engine, pull requests merged in 2025-04, with the labels that each got.

#1274 fix: Modify schema panel to close logic
  packages/plugins/schema/src/Main.vue
Labels: bug

#1246 fix: style backfill and right click to activate panel
  packages/canvas/container/src/components/CanvasMenu.vue
  packages/layout/src/DesignSettings.vue
  packages/layout/src/styles/vars.less
  packages/register/src/constants.ts
  packages/register/src/hooks.ts
  packages/settings/styles/index.ts
  packages/settings/styles/src/components/classNamesContainer/index.vue
  packages/settings/styles/src/js/index.ts
  packages/settings/styles/src/js/useStyle.ts
Labels: bug

#1267 fix: some version issue
  packages/canvas/container/src/keyboard.ts
  packages/common/component/PluginPanel.vue
  packages/plugins/i18n/src/Main.vue
  packages/settings/styles/src/components/spacing/SpacingGroup.vue
Labels: bug

#1280 fix: Modify some version issue
  packages/engine-cli/template/designer/env/.env.alpha
  packages/engine-cli/template/designer/env/.env.development
  packages/engine-cli/template/designer/env/.env.production
  packages/plugins/block/src/BlockSetting.vue
  packages/plugins/block/src/Main.vue
  packages/plugins/page/src/Tree.vue
Labels: bug

#1285 fix: save button red dot shows exception
  packages/common/js/http.js
Labels: bug

#1292 fix: globalState inCorrect spell
  packages/plugins/materials/src/composable/useResource.ts
Labels: bug

#1253 fix: del event should trigger change event
  packages/settings/events/src/components/BindEvents.vue
Labels: bug

#1254 fix: getRenderer could be null before canvas init
  packages/canvas/container/src/container.ts
Labels: bug

#1302 fix: 修复HtmlAttributesConfigurator配置组件样式问题
  packages/configurator/src/html-attributes-configurator/HtmlAttributesConfigurator.vue
Labels: bug

#1306 feat: add layoutConfig and config demo
  designer-demo/registry.js
  designer-demo/src/plugins/script/Main.vue
  designer-demo/src/plugins/script/index.ts
  designer-demo/src/plugins/script/js/method.ts
  designer-demo/src/plugins/script/meta.js
  designer-demo/src/plugins/script/styles/vars.less
  packages/design-core/registry.js
  packages/layout/index.ts
  packages/layout/src/DesignPlugins.vue
  packages/layout/src/DesignSettings.vue
  packages/layout/src/DesignToolbars.vue
  packages/layout/src/composable/useLayout.js
  packages/layout/src/defaultLayout.js
  packages/register/src/common.ts
Labels: enhancement

#1307 feat: tree-shaking demo
  designer-demo/registry.js
  designer-demo/removedRegistry.json
  designer-demo/vite.config.js
  packages/build/vite-config/package.json
  packages/build/vite-config/src/default-config.js
  packages/build/vite-config/src/vite-plugins/treeShakingPlugin.js
  packages/design-core/registry.js
  packages/design-core/vite.config.js
  packages/toolbars/fullscreen/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/view-setting/package.json
Labels: enhancement

#1294 fix: resolve TinyCheckboxGroup and video issue
  designer-demo/public/mock/bundle.json
Labels: bug

#1249 feat: keep same appid both mock server and java server
  README.md
  README.zh-CN.md
  docs/api/backend-api/material-center.md
  docs/solutions/server-deployment-solution.md
  mockServer/src/assets/json/appinfo.json
  mockServer/src/assets/json/sources.json
  mockServer/src/database/blockCategories.db
  mockServer/src/database/blockGroups.db
  mockServer/src/database/defaultData/default.db
  mockServer/src/database/pages.db
  mockServer/src/mock/get/app-center/apps/detail/1.json
  mockServer/src/mock/get/app-center/apps/extension/delete.json
  mockServer/src/mock/get/app-center/apps/extension/list.json
  mockServer/src/mock/get/app-center/sources/list/1.json
  mockServer/src/mock/get/app-center/v1/apps/schema/1.json
  mockServer/src/mock/post/app-center/apps/update/1.json
  mockServer/src/mock/post/app-center/sources/update.json
  mockServer/src/services/pages.js
  packages/build/vite-config/src/default-config.js
  packages/design-core/registry.js
  packages/engine-cli/src/commands/create.js
  packages/engine-cli/src/index.js
  scripts/buildMaterials.mjs
Labels: enhancement

#1291 fix: genCodeUnitTest failed
  packages/vue-generator/src/generator/vue/sfc/generateAttribute.js
  packages/vue-generator/test/testcases/element-plus-case/element-plus-case.test.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/http/axios.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/src/lowcodeConfig/dataSource.js
  packages/vue-generator/test/testcases/element-plus-case/expected/appdemo01/vite.config.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/http/axios.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/lowcodeConfig/dataSource.js
  packages/vue-generator/test/testcases/generator/expected/appdemo01/src/views/createVm.vue
  packages/vue-generator/test/testcases/generator/expected/appdemo01/vite.config.js
  packages/vue-generator/test/testcases/generator/generateApp.test.js
  packages/vue-generator/test/testcases/sfc/accessor/accessor.test.js
  packages/vue-generator/test/testcases/sfc/accessor/expected/Accessor.vue
  packages/vue-generator/test/testcases/sfc/accessor/schema.json
  packages/vue-generator/test/testcases/sfc/case01/expected/FormTable.vue
Labels: bug

#1296 fix: del event should trigger change event
  packages/settings/events/src/components/BindEvents.vue
Labels: bug

#1309 fix: Remove the message indicating that the token is empty in the AI dialog box
  packages/plugins/robot/src/Main.vue
Labels: bug

#1299 fix: importSchema will lose currentPage info
  packages/canvas/DesignCanvas/src/api/useCanvas.ts
Labels: bug

#1289 Fix the error reporting issue of the block on the parent page.
  packages/design-core/src/preview/src/preview/Preview.vue
Labels: bug

#1313 feat: material config support object
  packages/plugins/materials/src/composable/useMaterial.ts
Labels: enhancement

#1315 v2.5.0-alpha.2
  designer-demo/package.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/layout/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: ignore-for-release

#1303 feat: TinyPopeditor add auto-lookup attr
  designer-demo/public/mock/bundle.json
Labels: enhancement

#1310 fix: Remove the message indicating that the token is empty in the AI dialog box
  packages/plugins/robot/src/Main.vue
Labels: bug

#1308 feat: ai add deepseek
  packages/plugins/robot/src/js/robotSetting.ts
Labels: enhancement

#1318 feat: del useless layout toolbar
  packages/build/vite-config/src/vite-plugins/devAliasPlugin.js
  packages/design-core/package.json
  packages/toolbars/layout/assets/test.png
  packages/toolbars/layout/index.ts
  packages/toolbars/layout/meta.js
  packages/toolbars/layout/mock/test.ts
  packages/toolbars/layout/package.json
  packages/toolbars/layout/src/Main.vue
  packages/toolbars/layout/test/test.ts
  packages/toolbars/layout/vite.config.ts
  tsconfig.app.json
Labels: enhancement

#1323 fix: url unchanged after create block
  mockServer/src/routes/main-routes.js
  mockServer/src/services/blockCategory.js
  packages/plugins/block/src/SaveNewBlock.vue
  packages/plugins/block/src/composable/useBlock.ts
  packages/plugins/block/src/js/blockSetting.tsx
  packages/plugins/materials/src/composable/useResource.ts
Labels: bug

#1328 feat: remove code to base64 for performance issue
  packages/canvas/init-canvas/init-canvas.ts
  packages/canvas/scripts/vite-plugin-separate-build.ts
Labels: enhancement

#1326 refactor: optimize Vue canvas interaction logic
  designer-demo/engine.config.js
  designer-demo/public/mock/bundle.json
  packages/canvas/container/index.ts
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/container/src/components/CanvasAction.vue
  packages/canvas/container/src/components/CanvasDivider.vue
  packages/canvas/container/src/components/CanvasHover.vue
  packages/canvas/container/src/components/CanvasInsertLine.vue
  packages/canvas/container/src/components/CanvasResizeBorder.vue
  packages/canvas/container/src/components/CanvasRouterJumper.vue
  packages/canvas/container/src/components/CanvasViewerSwitcher.vue
  packages/canvas/container/src/composables/useMultiSelect.ts
  packages/canvas/container/src/container.ts
  packages/canvas/container/src/interactions/common.ts
  packages/canvas/container/src/interactions/html-interactions.ts
  packages/canvas/container/src/interactions/index.ts
  packages/canvas/container/src/interactions/vue-interactions.ts
  packages/canvas/container/src/interactions/vue-rect.ts
  packages/canvas/container/src/keyboard.ts
  packages/canvas/render/src/render.ts
  packages/canvas/render/src/runner.ts
  packages/plugins/tree/src/Main.vue
  packages/toolbars/save/src/js/index.ts
Labels: refactoring

#1327 feat: preview support auto update
  designer-demo/src/preview.js
  packages/common/js/preview.js
  packages/common/package.json
  packages/design-core/package.json
  packages/design-core/src/preview/src/Toolbar.vue
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/design-core/src/preview/src/preview/generate.js
  packages/design-core/src/preview/src/preview/http.js
  packages/design-core/src/preview/src/preview/importMap.js
  packages/design-core/src/preview/src/preview/usePreviewCommunication.ts
  packages/design-core/src/preview/src/preview/usePreviewData.ts
  packages/plugins/block/src/BlockSetting.vue
  packages/plugins/page/src/PageHistory.vue
  packages/plugins/page/src/composable/usePage.ts
  packages/toolbars/preview/meta.js
  packages/toolbars/preview/src/Main.vue
Labels: enhancement

#1248 feat: multi-node right menu
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/DesignCanvas/src/api/useCanvas.ts
  packages/canvas/container/src/CanvasContainer.vue
  packages/canvas/container/src/components/CanvasMenu.vue
  packages/canvas/container/src/composables/useMultiSelect.ts
  packages/canvas/container/src/container.ts
  packages/plugins/block/src/composable/useBlock.ts
Labels: enhancement

#1321 feat: remove code to base64 for performance issue
  packages/canvas/init-canvas/init-canvas.ts
  packages/canvas/scripts/vite-plugin-separate-build.ts
Labels: enhancement

#1335 feat：add TinyTransfer component material
  designer-demo/public/mock/bundle.json
  packages/design-core/assets/transfer.svg
Labels: enhancement

#1261 feat: preview support auto update
  docs/README.md
  docs/api/frontend-api/preview-api.md
  docs/catalog.json
  packages/common/js/preview.js
  packages/common/package.json
  packages/design-core/package.json
  packages/design-core/src/preview/src/Toolbar.vue
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/design-core/src/preview/src/preview/generate.js
  packages/design-core/src/preview/src/preview/http.js
  packages/design-core/src/preview/src/preview/importMap.js
  packages/design-core/src/preview/src/preview/usePreviewCommunication.ts
  packages/design-core/src/preview/src/preview/usePreviewData.ts
  packages/plugins/block/src/BlockSetting.vue
  packages/plugins/page/src/PageHistory.vue
  packages/plugins/page/src/composable/usePage.ts
  packages/toolbars/preview/meta.js
  packages/toolbars/preview/src/Main.vue
Labels: documentation, enhancement

#1337 feat/importMapLocalPlugin
  .gitignore
  designer-demo/env/.env.alpha
  designer-demo/env/.env.development
  designer-demo/env/.env.localCDN.example
  designer-demo/package.json
  designer-demo/public/mock/bundle.json
  designer-demo/tests/localCdnBasic.test.js
  designer-demo/tests/localCdnBundleDeps.test.js
  designer-demo/tests/localCdnCustomConfig.test.js
  designer-demo/tests/utils/envHelpers.js
  designer-demo/vitest.config.js
  docs/README.md
  docs/catalog.json
  docs/solutions/import-map-local.md
  packages/build/vite-config/package.json
  packages/build/vite-config/src/default-config.js
  packages/build/vite-config/src/localCdnFile/copyBundleDeps.js
  packages/build/vite-config/src/localCdnFile/copyImportMap.js
  packages/build/vite-config/src/localCdnFile/importMapLocalPlugin.js
  packages/build/vite-config/src/localCdnFile/index.js
  packages/build/vite-config/src/localCdnFile/locateCdnNpmInfo.js
  packages/build/vite-config/src/localCdnFile/replaceImportPath.mjs
  packages/build/vite-config/src/vite-plugins/cdnCopyPlugin.js
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/DesignCanvas/src/importMap.ts
  packages/common/js/import-map.json
  packages/common/js/importMap.js
  packages/common/package.json
  packages/common/vite.config.ts
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/Preview.vue
  packages/design-core/src/preview/src/preview/importMap.js
  packages/design-core/src/preview/src/preview/srcFiles.js
  packages/design-core/vite.config.js
Labels: documentation, enhancement

#1339 feat/add refresh material api
  packages/plugins/materials/src/composable/useMaterial.ts
  packages/plugins/materials/src/meta/component/src/Main.vue
Labels: enhancement

#1320 feat: add refresh material api
  packages/plugins/materials/src/composable/useMaterial.ts
  packages/plugins/materials/src/meta/component/src/Main.vue
Labels: enhancement

#1341 fix: Page Cleared: Save Operation Failed
  packages/canvas/DesignCanvas/src/api/useCanvas.ts
Labels: bug

#1344 fix: del not recommended cdn link
  docs/solutions/block-release-solution.md
Labels: bug, documentation

#1242 fix: localImportMap not works
  .gitignore
  designer-demo/env/.env.alpha
  designer-demo/env/.env.development
  designer-demo/env/.env.localCDN.example
  designer-demo/env/.env.production
  designer-demo/package.json
  designer-demo/public/mock/bundle.json
  designer-demo/tests/localCdnBasic.test.js
  designer-demo/tests/localCdnBundleDeps.test.js
  designer-demo/tests/localCdnCustomConfig.test.js
  designer-demo/tests/utils/envHelpers.js
  designer-demo/vitest.config.js
  docs/README.md
  docs/catalog.json
  docs/solutions/import-map-local.md
  packages/build/vite-config/package.json
  packages/build/vite-config/src/default-config.js
  packages/build/vite-config/src/localCdnFile/copyBundleDeps.js
  packages/build/vite-config/src/localCdnFile/copyImportMap.js
  packages/build/vite-config/src/localCdnFile/importMapLocalPlugin.js
  packages/build/vite-config/src/localCdnFile/index.js
  packages/build/vite-config/src/localCdnFile/locateCdnNpmInfo.js
  packages/build/vite-config/src/localCdnFile/replaceImportPath.mjs
  packages/build/vite-config/src/vite-plugins/cdnCopyPlugin.js
  packages/canvas/DesignCanvas/src/DesignCanvas.vue
  packages/canvas/DesignCanvas/src/importMap.ts
  packages/common/js/import-map.json
  packages/common/js/importMap.js
  packages/common/package.json
  packages/common/vite.config.ts
  packages/design-core/package.json
  packages/design-core/src/preview/src/preview/http.js
  packages/design-core/src/preview/src/preview/importMap.js
  packages/design-core/src/preview/src/preview/srcFiles.js
  packages/design-core/src/preview/src/preview/usePreviewData.ts
  packages/design-core/vite.config.js
  packages/engine-cli/template/designer/env/.env.alpha
  packages/engine-cli/template/designer/env/.env.development
  packages/engine-cli/template/designer/env/.env.production
  scripts/updateTemplate.mjs
Labels: bug, documentation

#1348 fix: del useless deps
  packages/build/vite-config/package.json
Labels: bug

#1346 v2.5.0-rc.0
  designer-demo/package.json
  designer-demo/public/mock/bundle.json
  mockServer/package.json
  packages/block-compiler/package.json
  packages/blockToWebComponentTemplate/package.json
  packages/build/vite-config/package.json
  packages/build/vite-plugin-meta-comments/package.json
  packages/builtinComponent/package.json
  packages/canvas/package.json
  packages/common/package.json
  packages/configurator/package.json
  packages/design-core/package.json
  packages/engine-cli/package.json
  packages/engine-cli/template/designer/package.json
  packages/engine-cli/template/designer/public/mock/bundle.json
  packages/i18n/package.json
  packages/layout/package.json
  packages/plugins/block/package.json
  packages/plugins/bridge/package.json
  packages/plugins/datasource/package.json
  packages/plugins/help/package.json
  packages/plugins/i18n/package.json
  packages/plugins/materials/package.json
  packages/plugins/page/package.json
  packages/plugins/robot/package.json
  packages/plugins/schema/package.json
  packages/plugins/script/package.json
  packages/plugins/state/package.json
  packages/plugins/tree/package.json
  packages/plugins/tutorial/package.json
  packages/register/package.json
  packages/settings/design/package.json
  packages/settings/events/package.json
  packages/settings/panel/package.json
  packages/settings/props/package.json
  packages/settings/styles/package.json
  packages/svgs/package.json
  packages/theme/base/package.json
  packages/toolbars/breadcrumb/package.json
  packages/toolbars/clean/package.json
  packages/toolbars/collaboration/package.json
  packages/toolbars/fullscreen/package.json
  packages/toolbars/generate-code/package.json
  packages/toolbars/lang/package.json
  packages/toolbars/lock/package.json
  packages/toolbars/logo/package.json
  packages/toolbars/logout/package.json
  packages/toolbars/media/package.json
  packages/toolbars/preview/package.json
  packages/toolbars/redoundo/package.json
  packages/toolbars/refresh/package.json
  packages/toolbars/save/package.json
  packages/toolbars/setting/package.json
  packages/toolbars/themeSwitch/package.json
  packages/toolbars/view-setting/package.json
  packages/utils/package.json
  packages/vue-generator/package.json
  packages/webcomponent/package.json
Labels: release, ignore-for-release

#1350 feat: replace ui with tiny-robot
  packages/plugins/robot/index.ts
  packages/plugins/robot/package.json
  packages/plugins/robot/src/Main.vue
Labels: enhancement

#1351 feat: add mcp tool demo
  designer-demo/public/mock/bundle.json
  packages/canvas/DesignCanvas/index.ts
  packages/canvas/DesignCanvas/src/tools/addNode.ts
  packages/canvas/DesignCanvas/src/tools/changeNodeProps.ts
  packages/canvas/DesignCanvas/src/tools/delNode.ts
  packages/canvas/DesignCanvas/src/tools/getCurrentSelectedNode.ts
  packages/canvas/DesignCanvas/src/tools/getPageSchema.ts
  packages/canvas/DesignCanvas/src/tools/index.ts
  packages/canvas/DesignCanvas/src/tools/queryNodeById.ts
  packages/canvas/DesignCanvas/src/tools/selectSpecificNode.ts
  packages/canvas/package.json
  packages/layout/index.ts
  packages/layout/package.json
  packages/layout/src/composable/useLayout.ts
  packages/layout/src/tools/closePluginPanel.ts
  packages/layout/src/tools/getAllPlugins.ts
  packages/layout/src/tools/index.ts
  packages/layout/src/tools/openPluginPanel.ts
  packages/plugins/i18n/package.json
  packages/plugins/i18n/src/composable/index.ts
  packages/plugins/i18n/src/composable/tools/addI18n.ts
  packages/plugins/i18n/src/composable/tools/delI18n.ts
  packages/plugins/i18n/src/composable/tools/getAllI18n.ts
  packages/plugins/i18n/src/composable/tools/getI18n.ts
  packages/plugins/i18n/src/composable/tools/index.ts
  packages/plugins/i18n/src/composable/tools/updateI18n.ts
  packages/plugins/i18n/src/composable/useTranslate.ts
  packages/plugins/materials/index.ts
  packages/plugins/materials/package.json
  packages/plugins/materials/src/composable/useMaterial.ts
  packages/plugins/materials/src/tools/getComponentDetail.ts
  packages/plugins/materials/src/tools/getComponentList.ts
  packages/plugins/materials/src/tools/index.ts
  packages/plugins/page/index.ts
  packages/plugins/page/package.json
  packages/plugins/page/src/composable/usePage.ts
  packages/plugins/page/src/tools/addPage.ts
  packages/plugins/page/src/tools/changePageBasicInfo.ts
  packages/plugins/page/src/tools/delPage.ts
  packages/plugins/page/src/tools/editSpecificPage.ts
  packages/plugins/page/src/tools/getPageDetail.ts
  packages/plugins/page/src/tools/getPageList.ts
  packages/plugins/page/src/tools/index.ts
  packages/plugins/robot/package.json
  packages/plugins/robot/src/Main.vue
  packages/register/src/common.ts
  packages/register/src/index.ts
  pnpm-workspace.yaml
  temp-proxy-server/.gitignore
  temp-proxy-server/README.md
  temp-proxy-server/package.json
  temp-proxy-server/src/ai.js
  temp-proxy-server/src/builtinMcpServer.js
  temp-proxy-server/src/index.js
  temp-proxy-server/src/mcpServerManager.js
  temp-proxy-server/src/stdioMcpServer.js
  temp-proxy-server/src/utils.js
  temp-proxy-server/src/wsManager.js
Labels: enhancement

#1336 feat：add document
  docs/advanced-features/imgs/final-effect.gif
  docs/advanced-features/imgs/preview-1.png
  docs/advanced-features/imgs/preview-2.gif
  docs/advanced-features/imgs/preview-3.gif
  docs/advanced-features/imgs/preview-4.png
  docs/advanced-features/imgs/preview-5.png
  docs/advanced-features/imgs/preview-6.gif
  docs/advanced-features/imgs/route-1.gif
  docs/advanced-features/imgs/route-2.gif
  docs/advanced-features/imgs/route-3.png
  docs/advanced-features/imgs/route-4.gif
  docs/advanced-features/imgs/route-5.gif
  docs/advanced-features/imgs/route-6.png
  docs/advanced-features/imgs/route-7.gif
  docs/advanced-features/imgs/route-8.png
  docs/advanced-features/imgs/route-bar-1.png
  docs/advanced-features/imgs/route-bar-2.gif
  docs/advanced-features/page-support-nested-route.md
  docs/advanced-features/route-bar-clear-preview-page.md
  docs/advanced-features/route-bar-current-page-highlight.md
  docs/advanced-features/route-view-support-preview-subpage.md
  docs/basic-features/imgs/outline-tree-1.png
  docs/basic-features/imgs/outline-tree-2.gif
  docs/basic-features/imgs/outline-tree-3.png
  docs/basic-features/imgs/outline-tree-4.png
  docs/basic-features/imgs/outline-tree-5.png
  docs/basic-features/imgs/outline-tree-6.png
  docs/basic-features/imgs/outline-tree-7.gif
  docs/basic-features/imgs/outline-tree-8.png
  docs/basic-features/outline-tree.md
Labels: documentation, enhancement
